### PR TITLE
add ability to change progress update interval

### PR DESCRIPTION
**Pull request by ndao**
~250ms is too often for me. Added this to be able to configure the interval.

### CODE REVIEW

**Comment by mattapperson** [comment]
Any chance you could rebase this for us?

**Comment by mattapperson** [comment]
This PR will be closed by the end of the week if you dont currently have the time to rebase. You would be welcome to re-open at your convenience

**Comment by bsiddiqui** [comment]
@ndao if you don't have time to rebase, I can make a sep PR since I'd like this feature as well

**Comment by ndao** [comment]
@mattapperson, i think i fixed it. sorry for the bunch of commits. first time doing a PR 👅

**Pull request merged**
