### PR TITLE
Update NPM version to 0.9.1

### PR DESCRIPTION
**Pull request by larryranches**
There's new code in this library, let's make it available via NPM-install.

### CODE REVIEW

**Comment by mattapperson** [comment]
@notbrent

**Comment by mattapperson** [comment]
@brentvatne

**Comment by getnashty** [comment]
+1

**Comment by larryranches** [comment]
bumpppppp

**Comment by brentvatne** [comment]
@larryranches - @mattapperson has npm ownership now, so hopefully he can publish soon!

**Comment by aaronschubert0** [comment]
@mattapperson Would be good to get 1.0 with the new exoplayer

**Comment by mattapperson** [comment]
@aaronschubert agreed, just been a little crazy over here... just bought a new house and have been remodeling it. I'll get the new build published in the next few days though

**Comment by hellogerard** [comment]
FYI, the current version in `master` is 1.0.0, which IMO is correct. So I think that's the version we're talking about.

There's a couple other frequent crashes which have PRs for fixes. I think it best to get these into a 1.0.0 release as well, if possible.

#444 
#455 

_EDIT:_ I guess, for backwards compatibility, you could release 0.9.1 followed by 1.0.0 for all future versions.

**Comment by larryranches** [comment]
@hellogerard I agree, they should release 0.9.1 first for a fix that will resolve a lot of the issues users have been facing.

@mattapperson @brentvatne Is there a roadmap to 1.0.0 version? If it's not soon, I think it would be worth bumping the current version as this is pretty critical.

**Comment by Kielan** [comment]
Still has not been done, please, publish. current master branch is not working.

**Comment by brentvatne** [comment]
I have no involvement in this project anymore, @mattapperson's call on this

**Comment by mattapperson** [comment]
Sorry guys, been a little sluggish here due to life issues but I agree. I'll so my best to get a minor version bump to fix this released and then setup a 1.0 roadmap so we can get on that.

**Comment by larryranches** [comment]
@mattapperson Any update on this?

**Comment by mattapperson** [comment]
@larryranches npm is now at v 1.0.0

**Pull request closed without merging**
