### PR TITLE
Fixes bug where poster and video was displayed simultaneously

### PR DESCRIPTION
**Pull request by jensellfors**
When using poster image and not using absolute positioning of the Video element you end up with both video and poster elements. This was introduced in #1167. My fix to revert some changes but keep the benefits of no flashing.

This fix relies on `onReadyForDisplay` callback to hide the poster. It's been tested on iOS and ExoPlayer. I added it to DOM as well but haven't been able to test...

Fixes [1509](https://github.com/react-native-community/react-native-video/issues/1509)

### CODE REVIEW

**Comment by jensellfors** [comment]
@CHaNGeTe I'm happy with this one now, but need help testing. Especially on android and the ExoPlayer. We need to verify that `onReadyForDisplay` is called for all platforms, otherwise the poster won't be removed. What do you guys think of this solution?

**Comment by jensellfors** [comment]
@CHaNGeTe I just pushed a commit that hides the poster in `onLoad` as `onReadyForDisplay` is not implemented. (A good example why maintaining several platforms is hard ;p)

**Review by CHaNGeTe — APPROVED** [review]

**Review by n1ru4l — APPROVED** [review]
Legit!

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
"react-native-video": "^5.0.2"

React Native Android Black Screen For Android

**Pull request merged**
