### PR TITLE
Fix build with react-native 0.65

### PR DESCRIPTION
**Pull request by cuongweallnet**
Fix android build with react-native 0.65

### CODE REVIEW

**Comment by tommynordli** [comment]
For me it's the `android-scalablevideoview-1.0.4` package that's giving me problems in rn 0.65, not the exoplayer

**Comment by stigi** [comment]
Yes, I've opened this upstream issue but no movement on there yet.

- https://github.com/yqritc/Android-ScalableVideoView/issues/52

Anybody found a local workaround?

**Comment by stephane-r** [comment]
It would seem that the depo' (Android-ScalableVideoView) is no longer maintained :sob:  ?

**Comment by scottkz** [comment]
> Yes, I've opened this upstream issue but no movement on there yet.
> 
> * [Maven Repo after JCenter shutdown yqritc/Android-ScalableVideoView#52](https://github.com/yqritc/Android-ScalableVideoView/issues/52)
> 
> Anybody found a local workaround

`jcenter()` was removed from react-native v0.65+ it seems due to a shift to using maven central, `mavenCentral()`. You could add it back into your android project in android > build.gradle under:

``` javascript
allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter() <<---- Added Back Here >>
        maven { url 'https://www.jitpack.io' }
    }
}
```

However, there seems to be more than just a missing library reference going as I had to set up the library using the old linking method and the videos don't play consistently between the Android SDKs 28, 29, and 30. On my emulated Pixel 4 API 30 the screen stays black with audio. Once the controls disappear I can't click to get them back. If I grab the slider before they disappear and seek to a random time, then the video appears, but is frozen, just as an example. And this is all using cookie-cutter tooling. Most up-to-date VSCode v1.59.1, RN v0.65+, react-native-video v5.1.1, MacOS Big Sur, Node v14.17.5

There just seems like some weird stuff happening on Android. iOS is perfectly fine, however, as is usually the case. Hopefully, this is sussed out soon though.

**Comment by anhquan291** [comment]
> For me it's the `android-scalablevideoview-1.0.4` package that's giving me problems in rn 0.65, not the exoplayer

Same problem here. Any solutions yet? Thanks

**Comment by wbroek** [comment]
I would advice to define the package so other dependencies are not fetched/taken from jCenter anymore. Because jCenter does not allow any updates anymore of any package all other packages should be taken from mavenCentral for example.

You can add jcenter to `android/build.gradle` like this:
```
allprojects {
    repositories {
        .... # Keep the rest
        jcenter() {
            content {
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
    }
}
```

Hopefully somebody updates android-scalablevideoview to use another repository

**Review by graphtobinary — APPROVED** [review]

**Review by AndroidGuyDD — APPROVED** [review]

**Comment by matheusfaggi** [comment]
works fine for me, waiting eagerly for the merge request

**Comment by matheusfaggi** [comment]
works fine here!

**Comment by el-lsan** [comment]
any hope to have this released?

**Review by JiteshMiddha — APPROVED** [review]

**Comment by brocodedude** [comment]
> I would advice to define the package so other dependencies are not fetched/taken from jCenter anymore. Because jCenter does not allow any updates anymore of any package all other packages should be taken from mavenCentral for example.
> 
> You can add jcenter to `android/build.gradle` like this:
> 
> ```
> allprojects {
>     repositories {
>         .... # Keep the rest
>         jcenter() {
>             content {
>                 includeModule("com.yqritc", "android-scalablevideoview")
>             }
>         }
>     }
> }
> ```
> 
> Hopefully somebody updates android-scalablevideoview to use another repository

This fix isn't working for me, for some reason :( I'm having the same exact issue, I added the same exact code, I'm using RN 0.66, but i'm still getting the same error. Someone please help, thanks!

**Comment by jomarquez21** [comment]
With RN 0.66.1 works fine!
When will this pr be merged and a new version created?

**Comment by iagormoraes** [comment]
in android/build.gradle put this mavens google repository

```
maven { url "https://dl.google.com/android/maven2" }
```

When google releases it to `google()` or `mavenCentral()` you can remove it.

This will make the app to build with the dependencies of this PR

```
com.google.android.exoplayer:exoplayer:2.13.3
```

and

```
com.google.android.exoplayer:extension-okhttp:2.13.3
```

**Comment by karthikkncs14** [comment]
React native 0.66.4 it is not working 

Could not find com.google.android.exoplayer:exoplayer:2.9.2.
Required by:
    project :expo-av
Search in build.gradle files

**Comment by suhas-gaji** [comment]
JCenter is not working any more now. I am getting 403 from server for android-scalablevideoview-1.0.4 module. Any solution for this?
Also I found android-scalablevideoview-1.0.4 is available on https://jitpack.io/#yqritc/Android-ScalableVideoView. I tried adding this in build gradle of react-native-video in node _modules but no success, still getting same error

**Comment by lucis** [comment]
Yeah, adding `jCenter()` will soon not be a viable solution as it's expected to really shut down in February. I'm trying to remove all packages that are only available there and this library is one of them.

**Comment by schlaegerz** [comment]
> JCenter is not working any more now. I am getting 403 from server for android-scalablevideoview-1.0.4 module. Any solution for this? Also I found android-scalablevideoview-1.0.4 is available on https://jitpack.io/#yqritc/Android-ScalableVideoView. I tried adding this in build gradle of react-native-video in node _modules but no success, still getting same error

I am trying to get that one too, but the correct url is
https://jitpack.io/com/github/yqritc/Android-ScalableVideoView/v1.0.4/Android-ScalableVideoView-1.0.4.pom

I can't get gradle to look at that url since it has the extra "v" in the path. I can get it to look at 
https://jitpack.io/com/github/yqritc/Android-ScalableVideoView/1.0.4/Android-ScalableVideoView-1.0.4.pom
or
https://jitpack.io/com/github/yqritc/Android-ScalableVideoView/v1.0.4/Android-ScalableVideoView-v1.0.4.pom

But those are both not found

**Review by jimkhan — APPROVED** [review]

**Review by asagalovskiyLB — APPROVED** [review]

**Comment by RandomToni** [comment]
Annd.. adding jCenter() to build/gradle this is no longer a solution...

**Comment by Manil-SoftNEP** [comment]
> ```
> allprojects {
>     repositories {
>         mavenCentral()
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter() <<---- Added Back Here >>
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> ```
> 

Doing this works but it causes the app to crash on devices with low width. (For me it was Samsung Galaxy M 62)

**Pull request closed without merging**
