### PR TITLE
Android ExoPlayer cache

### PR DESCRIPTION
**Pull request by RalfNieuwenhuizen**
Basic implementation of ExoPlayer cache.

What is does is load the media into a SimpleCache at the apps cache directory `"/video"`, which can be read by the ExoPlayer.
The `exportVideo` method is meant for extracting a video file from the cache as an mp4 file, for example when you want to save it to the camera roll.

In order to make this work I have updated ExoPlayer to 2.8.2 which included breaking changes for `setSelectedTextTrack`.

TODO's:
- [ ] Fix `setSelectedTextTrack`
- [x] Maintain a maximum cache size
- [ ] Test on larger files
- [x] Test exportVideo

### CODE REVIEW

**Comment by n1ru4l** [comment]
@RalfNieuwenhuizen What about cache size and max file size?

**Comment by RalfNieuwenhuizen** [comment]
@n1ru4l good point. I've added this to the list of TODO's. For max file size I haven't seen any issues yet while testing with https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by cobarx** [comment]
I'd like to split the ExoPlayer update out into a separate PR. I would have done the upgrade sooner but ran into issues where it wanted to added an additional dependency on the support library or something like that.

If you want to create a new PR for the upgrade, I can take care of getting the text track code updated.

**Comment by RalfNieuwenhuizen** [comment]
@cobarx ah, turns out the update isn't necessary at all, since I'm not using `DownloadService` / `DownloadManager` anymore. Fixed in PR!

**Comment by djw27** [comment]
@RalfNieuwenhuizen I haven't looked into the details yet, but are you planning on supporting caching of HLS videos?

**Comment by cobarx** [comment]
@RalfNieuwenhuizen I wanted to give you a heads up that I merged the ExoPlayer 2.8.2 update (#1170) in case you want to use any of that stuff. I took care of the text track support.

Edit: add PR link

**Comment by alizbazar** [comment]
What are the blockers for this to be merged? Would love to get caching support for Android, too!

**Comment by CHaNGeTe** [comment]
@alizbazar It has a list of TODOs so I guess that's the reason

**Comment by cstranex** [comment]
Any word on this being completed?

**Comment by surethink** [comment]
when will this be merged? need it very much

**Comment by RalfNieuwenhuizen** [comment]
@hueniverse I have added some commits that help support a maximum cache size. That's all we have for now. Is this PR something you'd like to pick up?

**Comment by hueniverse** [comment]
@RalfNieuwenhuizen Much appreciated! Can you explain the items left on the TODO list above? Would you be able to update the documentation for this feature? Is it on by default or only enabled if manually configured?

**Pull request closed without merging**
