### PR TITLE
Update Android dependency to JitPack!

### PR DESCRIPTION
**Pull request by thang2162**
Updated Android-ScalableVideoView to use JitPack instead of JCenter as JCenter has been deprecated. https://www.jitpack.io/#thang2162/Android-ScalableVideoView

Thanks for opening a PR!
Since this is a volunteer project and is very active, anything you can do to reduce the amount of time needed to review and merge your PR is appreciated.
The following steps will help get your PR merged quickly:

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Focus the PR on only one area
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until it gets fixed.
If you're touching multiple different areas that aren't related, break the changes up into multiple PRs.

#### Describe the changes
Add a note describing what your PR does. If there is a change to the behavior of the code, explain why it needs to be updated.

### CODE REVIEW

**Comment by samuelpbowman** [comment]
+1; can we get this merged?

**Review by vanGalilea — APPROVED** [review]

**Comment by vanGalilea** [comment]
Can you please merge this?

**Comment by thang2162** [comment]
It says someone with write access has to merge this. The button to do so isn’t showing for me. Only option I’m getting is to close the request which makes sense since I’m not a maintainer. That being said I wasn’t sure who the previous comment was aimed at so I gave it shot. That obviously that didn’t do it, LOL.

**Comment by samuelpbowman** [comment]
@thang2162 Yeah I was hoping that the comments would get maintainers' attention; this change would be a huge help

**Review by freeboub — APPROVED** [review]

**Pull request merged**
