### PR TITLE
Fix issue using video player on FlatList - AVFoundationErrorDomain Code -11839

### PR DESCRIPTION
**Pull request by khanhld1910**
## What

Issue: https://github.com/react-native-video/react-native-video/issues/2475

Using `react-native-video` with FlatList has the issue being reported above

## Why

I think the cause is the video player is not being deallocated when the component (here is the FlatList item) being unmounted.

## How

I guess we could deallocate the Video player using `componentWillUnmount` and support calling `destroy` method by native module.

I tested with FlatList this way and it worked but I don't know object C and I think there could be another way to fix this issue so this PR is for notifying and ask for help on this issue.

Please help me review it and comment your better idea. Thanks a lot!

### CODE REVIEW

**Comment by hueniverse** [comment]
Thank you for the contribution. I'm in the same boat so would appreciate if anyone else could review this PR and provide feedback.

@khanhld1910 if you can create a sample app using https://github.com/hueniverse/react-native-video-test to show how the fix works, it would help validate it and get it merged quicker.

**Comment by khanhld1910** [comment]
@hueniverse Thank you! I've just tested my PR and it was having other issues still.
So I have to spend more time on this and I will create a sample app when it's better.
This issue was known for a while and hopefully there will be other people join in to help.

**Comment by hueniverse** [comment]
@khanhld1910 Ping me when it's ready for review!

**Comment by hueniverse** [comment]
Closing due to lack of response (from the original submitted or anyone else to review and rebase). If someone wants to pick this up please open a new PR that ports this code into the current master. We are doing our best to start clean with v6 which requires being a bit aggressive in closing stale PRs that are over a year old. Please don't consider this dismissing of your work and contribution - it's greatly appreciated.

**Pull request closed without merging**
