### PR TITLE
Fix: Can't disable subtitle on iOS when using type: disabled

### LINKED ISSUE #1144: iOS Sidecar VTT TextTrack toggling does not work
### Current behavior 
When attempting to toggle captions on and off via the selectedTextTrack prop, the video stops and freezes. I can no longer play the video after attempting to toggle. This happens for all videos I have tried.

Note, toggling captions works beautifully on Android.

### Reproduction steps
Currently I have a state variable for captions. I control the toggle through a button and set the type of selectedTextTrack to "disabled" or "title". 

i.e.
In the video component:
selectedTextTrack={this.state.captions}
textTracks={[
  {
    title: "English",
    language: "en",
    type: TextTrackType.VTT, // "text/vtt"
    uri: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
  },

In a button press event:
toggleCaptions = () => {
    this.setState({
      captions:{
        type: this.state.captions.type === "disabled" ? "title" : "disabled",
        value: "English"
      }
    })
  }

### Platform
Which player are you experiencing the problem on:
* iOS

### PR DESCRIPTION
**Pull request by nbennink**
This is a PR to fix #1144. 

### The original issue
When you select a textTrack it starts playing the video with subtitles. To disable these subtitle you can give the `setSelectedTextTrack={{type:'disabled'}}` to the Video component. This works correctly on Android, but on iOS it "freezes" the last known subtitle until the end of the video.

### How does this PR fix this?
There's been a discussion about how to fix this problem. A solution was to generate an empty VTT file with a package like RNFetchBlob. I think however that it's a better solution to generate this file in the Video component itself (since that's where the issue comes from). 

This PR adds an VTT file to the array of TextTracks. When the selectedTextTrack gets `type: disabled` it will select this track which makes the "old" track disappear.

Nothing changes in how you use texttracks. Something to note is that you can't load a completely empty VTT file. So there is a dot at the 98 hour timemark (basically never). 

Edit: I only load this empty VTT file when you actually have other texttracks as well. So you don't have the issue where it breaks Airplay.

### CODE REVIEW

**Review by danielmarino24i — APPROVED** [review]

**Comment by cobarx** [comment]
@nbennink This is a very clever and intelligent solution. I haven't had a chance to test this yet. My only concern would be whether the empty VTT track appears in the list of text tracks reported by onLoad. If so, we should filter it out.

**Comment by nbennink** [comment]
@cobarx Yes you are right. My latest commit removes the subtitle file from the onLoad event. So you can't see it in your front-end and the only way to select it, is by using `{type: "disabled"}` (just like Android).

**Comment by danielmarino24i** [comment]
Can this change conflict with this?
https://github.com/react-native-community/react-native-video/blob/d8df6fe01f70ab8bdb0dcc79a64f38b3f54be304/ios/Video/RCTVideo.m#L510

**Comment by nbennink** [comment]
I don't think that it's a problem, here in the [playerItemPrepareText method](https://github.com/react-native-community/react-native-video/pull/1468/files#diff-42e8804735be64e84d6dd1fb103210a1R410) the function gets returned when you don't give the video player text tracks using the `textTracks` prop. So the empty subtitle is not available when you don't give the player at least one text track.

This was done to prevent an issue where you can't Airplay a video that contains text tracks. I'm not using caching for my project right now, but I assume that it works the same here.

**Comment by nbennink** [comment]
So I recently discovered that this is not working on tvOS. It appears that [this](https://github.com/react-native-community/react-native-video/blob/d8df6fe01f70ab8bdb0dcc79a64f38b3f54be304/ios/Video/RCTVideo.m#L467) line returns nil so it skips the empty VTT file. I think that this is limitation of the tvOS file system or AVPlayer on tvOS. I'm looking for a solution to fix it. Let me know if someone has suggestions.

**Comment by CHaNGeTe** [comment]
@nbennink Just a quick question, are you using mp4? or adaptative streaming?
I have detected some issues with texttracks on Adaptative ones.

I was thinking in another approach for setting subtitles.

**Comment by nbennink** [comment]
@CHaNGeTe I am using mp4 files for subtitles and still have this issue. I'm not sure what the best option is to replace the current approach for subtitles. I'd like to fix the problem without the empty VTT file. 

Edit: I recently came back to this issue and tried again to come up with solution for tvOS but did not get it working. Anyone a suggestion?

**Comment by kotomono** [comment]
same problem here. why isnt this merged? tested and it works

**Pull request closed without merging**
