### PR TITLE
Replace PropTypes from react with form prop-types package

### PR DESCRIPTION
**Pull request by gitim**
see https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### CODE REVIEW

**Comment by SemonCat** [comment]
Need this, too!

**Comment by developer239** [comment]
thanks

**Comment by gpeal** [comment]
@mattapperson Can this be merged?

**Comment by gpeal** [comment]
@mattapperson This is a blocker for anybody who wants to upgrade past RN 0.42 (we're on 0.47-alpha now)

**Comment by pintocarlos** [comment]
When will this be published to the npm package? I am on 1.2.0 and I see that this has not been fixed there... Also the package.json on master is showing version 1.1.0

**Pull request merged**
