### PR TITLE
Fixed seekableDuration for CMTimeRange with non-numeric duration (#709)

### LINKED ISSUE #709: Errors with Live HLS Stream on iOS Only
Hello I am using react-native-video on iOS,
I have tried to play a live stream getting out from Wowza Streaming Engine (Which is one of the best in the world).
The video is being played perfectly in the background but i got too many errors with 
```
folly::toJson: JSON object value was a NaN or INF
2017-07-29 16:14:24.925 [fatal][tid:com.facebook.react.JavaScript] Error calling RCTEventEmitter.receiveEvent
```

**Video codec is : H264 , Audio: AAC
Xcode: 8.3.3
iOS 10.3 - iPhone 6**

Also i have tried to init a new project and installed "react-native-video" with a fresh project and i got the same issue.

Please is there any solution ?

### PR DESCRIPTION
**Pull request by n4kz**
Fixes #709

### CODE REVIEW

**Review by luco — APPROVED** [review]
This works perfect.

**Review by drewvolz — APPROVED** [review]
This fixes the `RCTEventEmitter folly::toJson: JSON object value was a NaN or INF` issue I've noticed with HLS streaming on iOS.

**Comment by drewvolz** [comment]
@mattapperson Can this be merged?

**Comment by drewvolz** [comment]
Thank you!

**Comment by wujunshan** [comment]
Thank you, you solve my life

**Comment by csotiriou** [comment]
I just installed 2.0.0 and this commit is not found in the NPM repo. has this been merged to NPM?

**Pull request merged**
