### PR TITLE
Exoplayer - removed black screen while loading

### PR DESCRIPTION
**Pull request by maboelsoud**
Removed "shutterView" because it purposely turns the screen to black while the video is loading. This phenomenon is bound to be hinder appearance, as the black screen looks jarring and out of place.

### CODE REVIEW

**Comment by maboelsoud** [comment]
@mattapperson can you review this?

**Comment by mattapperson** [comment]
@Mohamed-Abo-El-Soud I would rather see this as a prop to turn this on or off, times exist when this is preferable.

**Comment by maboelsoud** [comment]
I'll whip something up

**Comment by cobarx** [comment]
@Mohamed-Abo-El-Soud What sort of situations are you running into issues with it being jarring?

Did you want to get this PR updated to make the behavior optional? I'd like the black screen to be the default as at least IMO it makes sense in most situations.

**Comment by maboelsoud** [comment]
@cobarx 
I was trying to build an app which shows multiple videos. And one video plays at a time. Think of it like Instagram, as you scroll through your feed, a single video plays at a time (u load one video only for performance). Thing is, when the video is not playing, you gotta show something, anything. I can't just have a black screen, it looks ugly! 

So I put a thumbnail in-front of the video, and before the video starts playing, the thumbnail dissapears. But then another problem, when the video starts playing, you see thumbnail-then-black-screen-then-video. That looks jarring and weird. So I try to have a callback, when the first frame of the video loads, the thumbnail dissapears. But that doesn't work because the JavaScript thread is slower than native, so the video plays for a second before the thumbnail is removed.

In the end, I found that removing the black screen, fixed my problem nicely. This also allows you to put whatever you want, black screen, Pink screen, blue screen whatever. And also it seamlessly transitions from no-video to video while loading. If you want to put a custom loading screen, you can. So it's a win-win for everyone! What's not to like?

**Pull request closed without merging**
