### PR TITLE
Upgrade ExoPlayer to 2.13.2

### PR DESCRIPTION
**Pull request by armands-malejevs**
Upgrade ExoPlayer from 2.11.4 to 2.13.2 and fix any issues related to the upgrade and deprecated method use.

### CODE REVIEW

**Comment by ignaciosantise** [comment]
Hello @armadilio3! Im testing this change in my project, its working good but im having some problems when building in release mode (proguard enabled):

```
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor$PeekingInputReader: can't find superclass or interface android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.mediaparser.InputReaderAdapterV30: can't find superclass or interface android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find superclass or interface android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.MediaParserExtractorAdapter: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.chunk.MediaParserChunkExtractor: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor$PeekingInputReader: can't find referenced class android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.hls.MediaParserHlsMediaChunkExtractor$PeekingInputReader: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.mediaparser.InputReaderAdapterV30: can't find referenced class android.media.MediaParser$SeekableInputReader
com.google.android.exoplayer2.source.mediaparser.InputReaderAdapterV30: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$TrackData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$InputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$TrackData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced method 'int getSchemeInitDataCount()' in library class android.media.DrmInitData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced method 'android.media.DrmInitData$SchemeInitData getSchemeInitDataAt(int)' in library class android.media.DrmInitData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced field 'java.util.UUID uuid' in library class android.media.DrmInitData$SchemeInitData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$OutputConsumer
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$TrackData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$InputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$TrackData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$InputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30: can't find referenced class android.media.MediaParser$TrackData
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$DataReaderAdapter: can't find referenced class android.media.MediaParser$InputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$DataReaderAdapter: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$DataReaderAdapter: can't find referenced class android.media.MediaParser$InputReader
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$SeekMapAdapter: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$SeekMapAdapter: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$SeekMapAdapter: can't find referenced class android.media.MediaParser
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$SeekMapAdapter: can't find referenced class android.media.MediaParser$SeekMap
com.google.android.exoplayer2.source.mediaparser.OutputConsumerAdapterV30$SeekMapAdapter: can't find referenced class android.media.MediaParser$SeekPoint
com.google.android.exoplayer2.video.VideoFrameReleaseHelper: can't find referenced method 'void setFrameRate(float,int)' in library class android.view.Surface
```

build.gradle
```
shrinkResources true
minifyEnabled true
proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
```

**Comment by armands-malejevs** [comment]
@ignaciosantise We don't have any issues building our app in release with 2.13.2. Can you check if master branch works for you?

**Comment by androidparth90** [comment]
can this be merged please so that we can get to use the latest exo player. We are facing lot of issues on Android due to seek bar

**Comment by ignaciosantise** [comment]
> @ignaciosantise We don't have any issues building our app in release with 2.13.2. Can you check if master branch works for you?

Hi @armadilio3, master branch builds successfully, but still failing in this branch. Are you building your app with proguard enabled?

**Comment by zchwyng** [comment]
Any news on this?

**Comment by parwan-as** [comment]
I've also noticed an issue when rendering a list of ExoPlayer on RN, after a certain amount of videos rendered and depending on the resolution of the video the player is not loading anymore....We need either need to use a single instance of the video player or being able to release it with an API

**Pull request merged**
