### PR TITLE
New api

### PR DESCRIPTION
**Pull request by brentvatne**
WIP

### CODE REVIEW

**Comment by ghost** [comment]
Looking forward to this [public API](https://github.com/brentvatne/react-native-video/issues/14). If you need a beta tester just LMK. I have a need to programmatically play and pause video based on events coming over the RCT bridge. And, perhaps unrelated, this should help me with a bug I've experienced where looped video playback stops after the app is backgrounded and restored.

**Comment by brentvatne** [comment]
Thanks @jhabdas - can you create an issue for that? I'll try to get the new api sorted and push out a rc for you soon!

**Comment by brentvatne** [comment]
@johanneslumpe :cry:

**Comment by johanneslumpe** [comment]
Yeah we really need to get this done :/

**Comment by ghost** [comment]
Already some good headway. Keep up the great work guys. And, for what it's worth, I'm still seeing #44 on occasion though none of my internal beta testers have reported it yet.

**Comment by jamesfzhang** [comment]
Any updates on this?

**Comment by brentvatne** [comment]
@jamesfzhang - sorry no updates here, if anyone would like to pick up where the illustrious @johanneslumpe left off you are more than welcome!

**Comment by getsetbro** [comment]
I'm hoping to use this with mp3s.

**Comment by brentvatne** [comment]
this is too out of date :(

**Pull request closed without merging**
