### PR TITLE
Fix/avplayer release

### PR DESCRIPTION
**Pull request by CHaNGeTe**
Release AVPlayer instance. Fixes some errors about: Decoder busy, etc.

### CODE REVIEW

**Comment by CHaNGeTe** [comment]
Related issues:
https://github.com/react-native-community/react-native-video/issues/1785
https://github.com/react-native-community/react-native-video/issues/1774

**Comment by jensellfors** [comment]
@CHaNGeTe are you still active here? :) I think this PR looks legit. At least it shouldn't hurt to set to nil in dealloc

**Comment by CHaNGeTe** [comment]
Being honest, I am bit disappeared haha.
Let's move forward with that one then.
@cobarx @benoitdion any input for this one?

**Comment by enigmablue** [comment]
Hi yes, i'm also waiting for this - am getting -11839 avfoundation errors, especially with multiple videos that seems to be playing at the same time

**Comment by kdzapp** [comment]
Tested this branch w/o success in terms of fixing original issue. Any suggestions?
```
{ localizedDescription: 'Cannot Decode',
     domain: 'AVFoundationErrorDomain',
     localizedFailureReason: 'The decoder required for this media is busy.',
     localizedRecoverySuggestion: 'Stop any other actions that decode media and try again.',
     code: -11839 },
```

**Comment by dancixx** [comment]
Any update on this issue?

**Comment by dancixx** [comment]
This can be useful: https://github.com/abuelwafa/react-native-modern-video-player

**Pull request closed without merging**
