### PR TITLE
Added tvOS paltform support

### PR DESCRIPTION
**Pull request by JulienKode**
- Add tvOS platform 
- Update readme to setup react-native-video on tvOS

### CODE REVIEW

**Review by Kureev — CHANGES_REQUESTED** [review]
I have a feeling that this PR has been made on top of #681. Even though I understand the situation, I'd rather update README in #681 and ship it in one go.

**Comment by JulienKode** [comment]
Ok no problem,

You can't close #681 and merge #682 when it's ready ?

I've made that if you don't want to merge the Readme. So you have a choice between two

**Review by Kureev — APPROVED** [review]

**Comment by jbreemhaar** [comment]
Would love to have this added 👍 
React-native-video works great on tvOS.

**Comment by FullstackJack** [comment]
Let's merge this and close #573 and #614 which do the same sans podspec and readme updates.

**Comment by Kureev** [comment]
Hey @mattapperson, can you take a look on this one?

**Comment by mattapperson** [comment]
LGTM

**Pull request merged**
