### PR TITLE
feat!(android): exit fullscreen mode after finishing video playback

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
## Summary
We don't need to exit fullscreen mode after finishing video playback because the user might be using repeat mode. This way, they won't need to interact with their phone after the video finishes.

### Motivation
Fix this issue [3703](https://github.com/TheWidlarzGroup/react-native-video/issues/3703).

## Test plan

### CODE REVIEW

**Review by KrzysztofMoch — COMMENTED** [review]
I have few questions:
- Do we have same behaviour on iOS ?
- What is default behaviour on android ?
- This can be breaking behaviour (I guess, but not sure) so maybe we should exit when `repeat=false`

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch
About the first question: On iOS, after finishing the video it doesn't exit fullscreen mode.
For the second question: The default behavior on Android depends on the player. I checked with different players. One of them exits fullscreen mode after finishing, while another doesn't.
Third question: I think we can apply this change on Android because we should have the same behavior on both OS (iOS and Android).
Imagine a user wants to see a list of movies. The user start watching the first movie in fullscreen mode. When the first video finishes, another video starts immediately, but the player exits fullscreen mode. As a result, the user has to activate fullscreen mode again.

Finally, I think it's better to not exit fullscreen mode after finishing video playback.
wdyt?

**Comment by freeboub** [comment]
Good explanation which justify the change. Agreed with @KrzysztofMoch , this behavior change is a breaking behavior it should be warned in release note !

**Review by freeboub — APPROVED** [review]

**Comment by KrzysztofMoch** [comment]
I would like to change this to 
- if repeat is `false` we exit fullscreen after video finish
- if repeat is `true` we don't exit fullscreen 

WDYT ? @seyedmostafahasani

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch I agree with you. 

What do you think about the point below?

Imagine a user wants to see a list of movies. The user start watching the first movie in fullscreen mode. When the first video finishes, another video starts immediately, but the player exits fullscreen mode. As a result, the user has to activate fullscreen mode again.

**Review by KrzysztofMoch — APPROVED** [review]
Okay fair point

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch I think we don't need to exit full-screen mode automatically. I guess the user can exit it if they want to.

**Pull request merged**
