### PR TITLE
fix(android): resolve a release issue with DefaultDashChunkSource

### LINKED ISSUE #4092: [BUG] Android: Type androidx.media3.exoplayer.dash.DefaultDashChunkSource$Factory is defined multiple times
### Version

6.4.4

### What platforms are you having the problem on?

Android

### System Version

Generating bundle

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

After upgrading from `6.4.3` to `6.4.4` I started getting this error when trying to create a signed bundle:

```
Type androidx.media3.exoplayer.dash.DefaultDashChunkSource$Factory is defined multiple times: [path-to-project]/node_modules/react-native-video/android/buildOutput_a15d4dee7fc4eda61b91308cbb6a2e72/.transforms/c8f30f85078ac0af2a73b555487223f1/transformed/release/androidx/media3/exoplayer/dash/DefaultDashChunkSource$Factory.dex, [path-to-project]/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex
```

It does not happen when running the app on the simulator

### Reproduction

_No response_

### Reproduction

Step to reproduce this bug are: 
Create a signed bundle release with new version 6.4.4

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
### Motivation
Fix #4092.

## Test plan

### CODE REVIEW

**Comment by seyedmostafahasani** [comment]
@freeboub @KrzysztofMoch 
If you have time, please release a new version with this change, as some users are unable to release a new version of their app with the latest version

**Comment by freeboub** [comment]
Yes I saw, I will check this afternoon, but I don't like this change it would be better to fix it on the gradle side, around the exclude call

**Comment by freeboub** [comment]
I cannot accomplish what I was expecting to do. let's merge this PR then.
The issue that exclude in the gradle file doesn't exclude .kt files. I tried to rework to use srcDirs instead of excludes, but unfortunnatlly, I cannot make it work as is...
Let's merge this PR as this is urgent. I will try to remove the stubs latter on.

**Review by freeboub — APPROVED** [review]

**Comment by seyedmostafahasani** [comment]
@freeboub 
Thank you 🙏.

**Pull request merged**
