### PR TITLE
chore: update docs link

### PR DESCRIPTION
**Pull request by moskalakamil**
## Summary
`thewidlarzgroup.github.io/react-native-video` -> `docs.thewidlarzgroup.com/react-native-video`
### Motivation
Updated all references to the documentation link throughout the entire application
### Changes
Replaced documentation links
## Test plan

### CODE REVIEW

**Comment by KrzysztofMoch** [comment]
@moskalakamil is this PR still this draft ?

**Comment by moskalakamil** [comment]
> @moskalakamil is this PR still this draft ?

Hey @KrzysztofMoch, yes - I need to check one more thing

**Comment by moskalakamil** [comment]
@KrzysztofMoch ready 👍

**Comment by freeboub** [comment]
@moskalakamil I think you missed some files

Capture d’écran 2024-11-05 à 23 00 20

**Comment by moskalakamil** [comment]
@freeboub thanks for vigilance! I'll check this tomorrow

**Comment by moskalakamil** [comment]
Updated

**Review by KrzysztofMoch — APPROVED** [review]
LGTM

**Pull request merged**
