### PR TITLE
RN 0.10 compatibility: switch to returning an array from customDirectEventTypes

### PR DESCRIPTION
**Pull request by jsierles**

### CODE REVIEW

**Comment by jsierles** [comment]
One issue - this example's video is black now, although audio plays fine.

broken on 0.10: https://rnplay.org/apps/-s5yiA
working on 0.8: https://rnplay.org/apps/NVtcUQ

**Comment by mfkp** [comment]
:+1: this works for me (tested with a video with no audio)

**Comment by jsierles** [comment]
Cool - could you put an example on rnplay.org that works for you using the 0.10 release?

**Comment by brentvatne** [comment]
thanks dude!

**Comment by brentvatne** [comment]
published in 0.6.0

**Pull request merged**
