### PR TITLE
feat(android): upgrade dependencies / media3 1.4.1 / androidxCore to 1.13.1 / androidxActivity 1.8.2

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
## Summary
Updated `media3`, `core`, and `activity` dependencies for AndroidX.

### Motivation
Fix potential issues related to version compatibility.

## Test plan
Test the sample app and build it in release mode.

### CODE REVIEW

**Review by freeboub — APPROVED** [review]

**Comment by freeboub** [comment]
I approuve, but I am afraid of compatibility with old react native versions. let see

**Comment by seyedmostafahasani** [comment]
I will test it with old version of react native.

**Comment by freeboub** [comment]
> I will test it with old version of react native.

The tvos sample uses old rn version! :)

**Comment by seyedmostafahasani** [comment]
@freeboub 
I created a new app with version 0.69.0 and ran the app with these changes. Everything works correctly, and I also built the app in release mode.

**Comment by freeboub** [comment]
> @freeboub 
> I created a new app with version 0.69.0 and ran the app with these changes. Everything works correctly, and I also built the app in release mode.

Ok, thank you for the tests, let's go with this !

**Pull request merged**
