### PR TITLE
issue 310 - Added a new property, ignoreSilentSwitch. 

### PR DESCRIPTION
**Pull request by duhseekoh**
When true, audio will play even when the silent switch on an iOS device is set to silent. When false, the audio will toggle with the silent switch. Sets the AVAudioSession to either playback or ambient.

Essentially, this... https://github.com/react-native-community/react-native-video/issues/310

If you guys are good with this I'll update the example project and readme.

### CODE REVIEW

**Comment by mattapperson** [comment]
I like this, but could you please update the readme noting this as an iOS only feature?

**Comment by duhseekoh** [comment]
Yea, I'll add to the readme and update the example project in the next couple of days.

**Comment by mattapperson** [comment]
Thanks! You rock!

**Comment by duhseekoh** [comment]
Made the example app and readme changes: 

image

**Comment by duhseekoh** [comment]
Just realized, no matter what, this is going to take over the audio session settings, even if the property isn't set.

Hmm. It might make sense to have an enum setting instead of the boolean value.

Something like:
```
<Video ... audioMode= 'ambient' | 'playback'
// instead of
<Video ... ignoreSilentSwitch = true | false
```

That way if audioMode isn't set, then it won't take over apps audio just because a video exists in the app.

**Comment by SemonCat** [comment]
This feature is useful,

any reason not merge it?

**Comment by mattapperson** [comment]
@SemonCat because as @duhseekoh pointed out, another API might be better

**Comment by larryranches** [comment]
@duhseekoh Great stuff!  Do you have any updates on changing the ignoreSilentSwitch bool to a Api that accepts an enum?

**Comment by alexanderjarvis** [comment]
I'm also looking at something similar to this. What this doesn't handle is multiple videos.

**Comment by GeoffreyPlitt** [comment]
Any update on this?

**Comment by GeoffreyPlitt** [comment]
My company has created a $200 bounty for this PR, hoping someone can fix the issues soon. https://www.bountysource.com/issues/37409911-add-playwhilemuted-property

**Comment by bsiddiqui** [comment]
@duhseekoh are you still interested in merging this? If not, I'm happy to update the api

**Comment by duhseekoh** [comment]
Yea looking back at this I'm good with merging it. We can't have this
library be the end all be all for sound management for an application, so a
boolean property to ignore the silent switch makes sense.

That being said I think there is a future here that handles sound
management for multiple videos on screen at one time, multiple sound
options, etc... it just depends on the level of sophistication we want in
this package and how much control we give through its API (preferably a
limited surface area).

**Comment by alexanderjarvis** [comment]
I created a version of this that handles multiple mounted video components and only stops the audio session when they are all unmounted: https://github.com/drivetribe/react-native-video/blob/fork/ios/RCTVideoAudio.m

It may not be exactly what you need but perhaps by posting it here it helps someone.

**Comment by larryranches** [comment]
@duhseekoh @bsiddiqui Are you guys planning on merging this PR soon?

**Comment by duhseekoh** [comment]
Updates: Changed ignoreSilentSwitch to accept two string values, ignore and obey.
This accounts for the case where the user does not want to modify the audio session from a particular video instance. The user would not use the ignoreSilentSwitch property at all in that case.
Also, the audio session will only be updated when the video is unpaused, instead of whenever the video component has updated props. This allows for multiple videos to be on the screen, with the most recent video unpaused (aka played) being the video that has control over the audio session.

Would be great to have someone pull this down / into their project and test it.

**Comment by larryranches** [comment]
@duhseekoh Just tested this out and it's working perfectly in my project 👍  Thanks! Lets get this PR merged :)

**Comment by duhseekoh** [comment]
Great. @mattapperson - Anything else needed for a merge?

**Comment by akhan118** [comment]
> Updates: Changed ignoreSilentSwitch to accept two string values, ignore and obey.
> This accounts for the case where the user does not want to modify the audio session from a particular video instance. The user would not use the ignoreSilentSwitch property at all in that case.
> **Also, the audio session will only be updated when the video is unpaused, instead of whenever the video component has updated props.** This allows for multiple videos to be on the screen, with the most recent video unpaused (aka played) being the video that has control over the audio session.
> 
> Would be great to have someone pull this down / into their project and test it.

Thank you for working on this feature , I have it a set it to where the video is paused as soon as the video is loaded and I'm observing that `ignoreSilentSwitch="ignore"` is not being evaluated as described above.

 However If I removed ` paused={true} ` , `ignoreSilentSwitch="ignore"`  works as intended. 

How can I get `ignoreSilentSwitch="ignore"`  to work when using  ` paused={true} `  ?

example

```
 <Video
 source={{uri: videoUrl}}
  controls={true}
  ignoreSilentSwitch="ignore"
  fullscreenAutorotate={true}
  paused={true}
 />
```


Thank you

**Pull request merged**
