### PR TITLE
Update Readme to include onBuffer event (#2141)

### PR DESCRIPTION
**Pull request by laurenceunmind**
This PR adds documentation for the `onBuffer` callback function, resolving issue #2141.

### CODE REVIEW

**Comment by KingAmo** [comment]
`onBuffer`  callback's  payload  `isBuffering` is always false when you are seeking, is this a bug?

**Comment by Champkinz** [comment]
> `onBuffer` callback's payload `isBuffering` is always false when you are seeking, is this a bug?

Im having the same issue, is there a fix ?

**Comment by jakeorbtl** [comment]
> `onBuffer` callback's payload `isBuffering` is always false when you are seeking, is this a bug?

I am also experiencing this issue, but only on iOS. It works as expected for the Android ExoPlayer.

**Comment by jakeorbtl** [comment]
> > `onBuffer` callback's payload `isBuffering` is always false when you are seeking, is this a bug?
> 
> Im having the same issue, is there a fix ?

I came up with a workaround that seems to work for ios. Since the `onSeek` event seems to be called after the video has finished buffering you can use that event to find when buffering has ended. When you seek to an unplayable portion of the video, the `playableDuration` value passed to the `onProgress` event callback becomes 0. We can use this to determine when buffering due to seeking has begun.

```
const onProgress = (data) => {
    setCurrentTime(data.currentTime);
    setPlayableDuration(data.playableDuration);
    setSeekableDuration(data.seekableDuration);

    if (Platform.OS === 'ios') {
        if ((data.playableDuration < data.currentTime)) {
            setIsBuffering(true);
        } else {
            setIsBuffering(false);
        }
    }
};

const onSeek = () => {
    Platform.OS === 'ios' && setIsBuffering(false);
};
```
The `playableDuration` check in `onProgress` also handles buffering when not seeking, so it is not necessary to use `onBuffer` for ios.

Also make sure to add the following:
```
const onEnd = () => {
    setIsBuffering(false);
};
```
Otherwise, your isBuffering flag will remain true when you seek to the end of the video.

**Comment by hueniverse** [comment]
@laurenceunmind Mind rebasing so I can merge it?

**Comment by laurenceunmind** [comment]
> @laurenceunmind Mind rebasing so I can merge it?

Sure, done 👍

**Pull request merged**
