### PR TITLE
Fix repeat for exoplayer

### PR DESCRIPTION
**Pull request by radko93**
Repeat was not working for me when using exoplayer. I found the reason: `setRepeatModifier` method was called after [this line](https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L208) in `initializePlayer`. This might not be the best solution here, so I'm waiting for any suggestions.

### CODE REVIEW

**Comment by zachrnolan** [comment]
Would love to see this fix merged!

**Comment by radko93** [comment]
It's currently not possible to switch from `true` to `false` in this PR (video will loop forever), I've tried to investigate this issue but now waiting for the response here: https://github.com/google/ExoPlayer/issues/2899.

**Comment by radko93** [comment]
Seems that better repeat mechanism will be soon added to the Exoplayer (it's already on a dev branch), so probably we will ned to wait. I'm leaving this here PR for now.

**Comment by maboelsoud** [comment]
I think this is causing #643 as a side effect. #628 is no good either

**Comment by radko93** [comment]
@Mohamed-Abo-El-Soud I'm not sure if it's possible, I'm just doing something only when the video ends. As I said in the comment above, better repeat mechanism will be soon merged to exoplayer.

**Comment by maboelsoud** [comment]
@radko93 side question: why does there seem to be so many little bugs using the android exoplayer and mediaplayer, where ios don't seem to have them? Is it that the functionality is somewhat new on the android side?

**Comment by radko93** [comment]
@Mohamed-Abo-El-Soud Seems that exoplayer is still in development somehow. iOS is more mature and it's just one platform, it's always on Android.

**Comment by cobarx** [comment]
They added a `setRepeatMode` function to control repeat behavior in ExoPlayer 2.5.0. I've gone ahead and implemented this in #1036. Thanks for diving into this and finding out that ExoPlayer was going to support it.

**Pull request closed without merging**
