### PR TITLE
Updated to ExoPlayer 2.4.0, added support for playback rate change

### PR DESCRIPTION
**Pull request by mdrbohlav**

### CODE REVIEW

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by KongHsi** [comment]
When will this PR get merged?

**Comment by tonycai96** [comment]
@mattapperson My team really need the playback rate change feature (on Android), which our users find very important. If you could let us know if this PR will be merged in the near feature that would be great.

**Comment by mattapperson** [comment]
Merging as I see no issue but would like feedback before it gets published

**Comment by tonycai96** [comment]
changing rate is working for me

**Comment by RickDT** [comment]
This does not appear to be working for me on Android. The video still plays at 1x speed. My code:
```
<Video
  rate={0.5}
  source={require("../../test-media/test-small.mp4")}
  style={styles.backgroundVideo}
/>
```

**Pull request merged**
