### PR TITLE
add subtitles style support to 5.2.x

### PR DESCRIPTION
**Pull request by sam1463**
Thanks for opening a PR!
Since this is a volunteer project and is very active, anything you can do to reduce the amount of time needed to review and merge your PR is appreciated.
The following steps will help get your PR merged quickly:

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Focus the PR on only one area
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until it gets fixed.
If you're touching multiple different areas that aren't related, break the changes up into multiple PRs.

#### Describe the changes
Add a note describing what your PR does. If there is a change to the behavior of the code, explain why it needs to be updated.
Taking the changes from [this merged PR](https://github.com/react-native-video/react-native-video/pull/2759) and applying them to 5.2.x

### CODE REVIEW

**Comment by evoactivity** [comment]
Do we want to backport features? I understand fixing 5.2.X so it runs on later versions of react-native but taking features from 6 and backporting to 5.2 seems like something that would be managed as a personal fork.

What do you  think @freeboub?

**Comment by sam1463** [comment]
Certainly makes sense not to backport features to old, unsupported versions, and I'm fine with just relying on my own fork until I can update to v6, if that's the best route for the library.
However, since 5.2.1 is still the most recently published on npm, if there's no intent of feature parity with v6, it's probably best to clarify in the documents for this library that some features (such as subtitle styling support) aren't supported in the version available on npm.
It's counter-intuitive to install via yarn, follow the docs, and then have it not work because the version you got isn't actually the latest version of the library and doesn't include feature parity.

**Comment by evoactivity** [comment]
That's a good point about the docs.

The readme on NPM is the 5.2.X version which makes no mention of `subtitleStyle` feature but the readme on github doesn't make it clear on where to go for 5.2.X docs so it would be easy to end up on the v6 docs.

I've added a PR that is more clear about the current state of the repo
https://github.com/react-native-video/react-native-video/pull/2875

**Comment by freeboub** [comment]
I agree this is not intended to backport new featues to 5.X branch, but while there is no stable V6 release it can make sense...
@sam1463 If you don't already have your own fork I am ok to merge it and make a new release, please just add a note in changelog.

**Comment by sam1463** [comment]
@evoactivity Thanks for the readme updates!

@freeboub what do you mean by the second part of your comment? This is a PR from my own fork of this library. Do you want me to add a note in the changelog on my fork/this PR?

**Comment by freeboub** [comment]
@sam1463 if you have your own fork let's cancel this PR as this is already available on master.
I was requesting a note in changeLog to be able to merge this PR

**Comment by sam1463** [comment]
👍 closing this then

**Pull request closed without merging**
