### PR TITLE
Fix AudioManager memory leak by moving OnAudioFocusChangeListener

### PR DESCRIPTION
**Pull request by BasixKOR**
This PR patches RNV to no longer cause memory leaks by AudioManager holding a reference of ReactExoplayerView.

First, an explanation of how this fixes the leak: The AudioManager tracks its listeners using [`toString()` as the key of the listener.](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/media/java/android/media/AudioManager.java;drc=a5cfe59a5db654f0f9230bd63aa68f31d7cfc121;l=3949) However the listener in RNV's case, is a View, which has the toString method overridden. This causes the key to mismatch, failing to remove the listener properly on `abandonAudioFocusRequest`.

This fixes the leak by giving the listener its own class for the listener, preventing issues that arise from inheritance. After this patch memory leak should be fixed.

### CODE REVIEW

**Comment by BasixKOR** [comment]
The same fixes can be applied to 5.X line as well; fixing #1963.

**Comment by freeboub** [comment]
Thank you for this change! Is it possible to extract the OnAudioFocusChangedListener to a dedicated file please ?

**Comment by BasixKOR** [comment]
That would be great, I'll work on it this week!

**Comment by BasixKOR** [comment]
It seems like it would require some level of refactoring to decouple the listener completely, as it highly depends on the internals of the view. Although the refactoring of the project would be great I think it would be better reviewed separately from this PR. What do you think?

**Pull request merged**
