### PR TITLE
#836 Fix video endless loop when repeat set to false or not specified.

### PR DESCRIPTION
**Pull request by Romick2005**
On video end set player pause.

### CODE REVIEW

**Comment by hueniverse** [comment]
@nickfujita Is this fix correct? Should be a quick review and if yes, a simple patch of the new code. If not, please close.

**Comment by nickfujita** [comment]
yes this seems right. would allow people to remove their workarounds in #836 

please port to swift here:
https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L1046

**Comment by hueniverse** [comment]
@Romick2005 Can you rebase and change to swift?

**Comment by Romick2005** [comment]
@hueniverse No I can't, but you can do it on your own `self.setPaused(true);`

**Comment by hueniverse** [comment]
Closed in https://github.com/react-native-video/react-native-video/commit/553e51c63945931e2a5ce3a1665dbaa5c1f2f67e

**Comment by Romick2005** [comment]
Could it be just merged? As there are no progress and package stuck in alfa for a year?

**Pull request closed without merging**
