### PR TITLE
fix(android): handle aspect ratio for rotated videos

### LINKED ISSUE #3929: [BUG]: ResizeMode does not apply after the second play onwards when props repeat true
### Version

6.1.2

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

ResizeMode does not apply after the second play onwards when props repeat true.

https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/d4c4204d-14fc-47a3-ab58-8719f0aaf78d

```
import React from 'react'
import Video, { ResizeMode } from 'react-native-video'

import { LandingScreenProps } from './types'

export const LandingScreen: LandingScreenProps = () => {
  return (
    <Video
      source={{ uri: "https://d1c40hpuz0tre6.cloudfront.net/stories/01HZRFTRYCM19PZ49BE54Z4FSY.mp4" }}
      style={{ flex: 1 }}
      resizeMode={ResizeMode.COVER}
      controls
      repeat
    />
  )
}
```

### Reproduction

_No response_

### Reproduction

Step to reproduce this bug are: 
1. Play video with props repeat true.

### PR DESCRIPTION
**Pull request by moskalakamil**
## Summary
Adjust aspect ratio handling for rotated videos

Closes #3929
### Motivation
In certain cases, the height and width of videos were not adjusting correctly with rotation. This PR addresses this issue by properly handling aspect ratio adjustments based on rotation angles.
### Changes
Modified logic to switch height and width when the rotation angle is 90 or 270 degrees.
## Test plan

1. Run the example video with the repeat mode flag from the [following URL](https://d1c40hpuz0tre6.cloudfront.net/stories/01HZRFTRYCM19PZ49BE54Z4FSY.mp4).
2. Verify that the aspect ratio is correctly adjusted when the video rotates during playback.

### CODE REVIEW

**Review by freeboub — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]

**Comment by nicolaosm** [comment]
This issue is still happening on my end. We're on 6.5.0 and when we rotate on android the aspect ratio is messed up.

**Comment by freeboub** [comment]
> This issue is still happening on my end. We're on 6.5.0 and when we rotate on android the aspect ratio is messed up.

Can you provide a sample please ? Maybe follow up on a dedicated ticket ..

**Comment by nicolaosm** [comment]
Figured its from my project. Should be working fine in the library. Thanks @freeboub

**Comment by tamdvyounetgroup** [comment]
I found the problem. The solution is.
Screenshot 2024-09-24 at 14 50 31

**Comment by freeboub** [comment]
@tamdvyounetgroup A PR is welcome, thank you !

**Comment by freeboub** [comment]
@tamdvyounetgroup I missed to thank you for the patch, it has been integrated in last release !

**Pull request merged**
