### PR TITLE
Feature/android using ExoPlayer

### PR DESCRIPTION
**Pull request by huangmr**
This is a replacement PR with RN updated to version 0.28.0 (current latest version) for:
 https://github.com/brentvatne/react-native-video/pull/240

The purpose of this PR is to replace default android MediaPlayer with ExoPlayer (via using a library com.devbrackets.android:exomedia) in order to support adaptive video streaming (e.g. M-DASH, HLS etc) on the android side.

Other changes include:

update to latest react-native version (0.28.0) on java side.
fix a start up error in the android demo code.
update to latest android build tools (23.0.3), android studio (2.2.0), gradle (2.10).
Some side effects due to ExoPlayer (android only):

looping not seems to be supported natively by ExoPlayer, currently a quick workaround is provided by manually re-setting the video source to the player, so there will be a smoothness issue there.
scale modes changed to the ExoPlayer supported ones (center, center_inside, center_crop, fit_center, none), currently only center_inside, center_crop are supported, and default mode is none.
raw folder is (currently) not supported by ExoPlayer, instead they need to be moved to assets folder and use path like "asset:///video.mp4".

### CODE REVIEW

**Comment by mroswald** [comment]
@brentvatne Is there a chance to get this merged? We've tested the branch and it works great for us. Thanks!

**Comment by mattapperson** [comment]
@mroswald @huangmr seems there are some merge conflicts. As soon as you update those we will get the reviewed and merged

**Comment by huangmr** [comment]
@mattapperson @mroswald this PR is no longer maintained unfortunately, so will close it instead.

**Comment by GeoffreyPlitt** [comment]
@mroswald What did you end up doing? Having the same issue here.

**Pull request closed without merging**
