### PR TITLE
Support RN 0.39.2 and RN 0.40.0

### PR DESCRIPTION
**Pull request by g3r4n**
See : 
https://github.com/Microsoft/react-native-code-push/pull/670

### CODE REVIEW

**Comment by mehcode** [comment]
@brentvatne @jhabdas 

Can we please get this merged / released?

**Comment by ghost** [comment]
@AndrewJack I saw a thumbs down. Any reason in particular? I can help get the changes merged and coordinate with @brentvatne on the release. But before I do I'd like to hear from at least one other person these changes are working well for them after a fresh RN init and module link.

**Comment by AndrewJack** [comment]
@jhabdas I think it would be easier to not support older react native versions, given the frequency of releases (even if they are now monthly). 

However since this library hasn't been published recently, I can see this change being useful. If we could release more often then we could avoid doing things like this.

**Comment by ghost** [comment]
Thanks for the clarification @AndrewJack, and I agree. Pragmatically, if this supports more than one version I'll take it. Just need someone else to confirm it's working as expected on a fresh RN init with video linked.

**Comment by edmundito** [comment]
I'm happy either way, and I've been tracking other dependent modules that need to be updated to 0.40, and there's a general pattern that I'm ok with:

1. Make changes without backward compatible support
2. Bump the minor number
3. Update the README to denote what version is compatible with 0.39 or below.

**Comment by g3r4n** [comment]
I was not aware that community didn't like backward compatible support. I understand that is more efficient to support new version of RN. I will work on that.

**Comment by ghost** [comment]
Thanks @g3r4n. Sorry if you lost any time. I was okay with this PR so long as it could be verified functional with the latest version of RN. As for the community, and I'm sure I don't speak for everyone, it's unlikely to see much backwards compatibility being baked in modules unless they're extremely widely used or backed by funding like CodePush, at least until RN hits a major semantic version.

**Comment by g3r4n** [comment]
I'm new to open source so i have to learn. Thanks for the explanation !

**Comment by ghost** [comment]
No problem. Your contributions are appreciated regardless of experience level. I'm going to reopen this to increase visibility. As mentioned earlier, I will merge these changes and work to get the NPM module updated as soon as someone can prove out the functionality with the latest version of RN. Thanks again, @g3r4n. 😃

**Comment by g3r4n** [comment]
it seems that this PR will not be merge because the next release will only support RN >=0.40.0

**Pull request closed without merging**
