### PR TITLE
Fix(android): restart issue react76

### LINKED ISSUE #2693: Move startup props into a single configuration
# Feature Request

Create a new prop where all current props that are only used during initialisation and cannot be changed during runtime into a single configuration prop.

## Why it is needed

This will make it more clear to developer as to which props can be changed during runtime and which props can only be provided when creating the player. This will also simplify the initialisation logic to get rid of `postDelayed` calls etc.

## Tasks

- [x] textTracks (external subtitle tracks)
- [x] contentStartTime
- [X] drm
- [x] Ads props
- [x] bufferConfig
- [x] minLoadRetryCountModifier

### LINKED ISSUE #4261: [BUG]: toggling muted prop causes full rerender on RN 0.76.0
### Version

6.7.0

### What platforms are you having the problem on?

Android TV

### System Version

12

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

Toggling the muted prop causes the whole component to rerender and start the video again.

Downgrading RN back to 0.75.2 resolves the issue.

### Reproduction Link

_No response_

### Reproduction

Toggle the muted prop

### PR DESCRIPTION
**Pull request by freeboub**
## Summary
fix: https://github.com/TheWidlarzGroup/react-native-video/issues/4261
fix: https://github.com/TheWidlarzGroup/react-native-video/issues/2693

### Motivation
Fix issue on react native 0.76

### Changes
- move bufferConfig inside source 
- fix restart issue on react 0.76
- fix constness
- deprecate bufferConfig in root props
- update documentation
- upgrade expo exemple to expo 54 with new arch

## Test plan
Can be test with the expo sample

### CODE REVIEW

**Review by KrzysztofMoch — APPROVED** [review]
Amazing job! Can you tell me in short what part fixed issue on 0.76? Thank You!

**Comment by freeboub** [comment]
> Amazing job! Can you tell me in short what part fixed issue on 0.76? Thank You!

I don't know why but we receive multiple times setBufferConfig callback. As there was a "force restart playback" inside this function playback was restarting 🤷
Maybe an issue in react native but I did already plan to change that (it was possible that it causes some race conditions in initial start up).

**Comment by freeboub** [comment]
@KrzysztofMoch I will release that tonight!

**Review by moskalakamil — APPROVED** [review]
Nice!

**Comment by hongjae-eum** [comment]
@freeboub 

I wasn't using bufferConfig at all, and I didn't encounter this restart issue in version 6.8.0.

However, after the patch update to version 6.8.1, when I pause a video, the onLoad callback triggers, causing the video to return to the starting point.

Could there be any suspected changes in the patch that might be related to this?

**Comment by freeboub** [comment]
@hongjae-eum no it should not ... Do you use the last react native version ? 0.75 with newArch enabled ?

**Comment by freeboub** [comment]
@hongjae-eum maybe this line: https://github.com/TheWidlarzGroup/react-native-video/blob/dd78241b0d997e87a65f2f898c7059a72951e532/android/src/main/java/com/brentvatne/common/api/Source.kt#L104
Can you try to remove the condition locally ? I think it can be the issue. I missed to overload the equals in BufferConfig ..

**Comment by hongjae-eum** [comment]
@freeboub 

Commenting out that part(line 104) resolves the restart issue! If that part is indeed the problem, it would be great if a patch could be released quickly.

**Comment by freeboub** [comment]
Yep, I will do it tonight, ping @KrzysztofMoch

**Comment by freeboub** [comment]
@hongjae-eum here is the fix: https://github.com/TheWidlarzGroup/react-native-video/pull/4305
It has already been released !
Thank you for the quick feedback !

**Pull request merged**
