### PR TITLE
iOS fixes

### LINKED ISSUE #3166: [iOS] Memory leaks
# Bug
Mount then unmount Video component result in swift init called but deinit is never called 

## Platform
* iOS

## Environment info

React native info output:
```bash
System:
  OS: macOS 13.2
  CPU: (8) x64 Apple M1
  Memory: 25.48 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.9.1
    path: /var/folders/m6/g_g8x9mx6bsdd0z4bz2h649r0000gn/T/yarn--1688635068292-0.5680216196061589/node
  Yarn:
    version: 1.22.19
    path: /var/folders/m6/g_g8x9mx6bsdd0z4bz2h649r0000gn/T/yarn--1688635068292-0.5680216196061589/yarn
  npm:
    version: 8.19.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/***/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "23"
      - "25"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-31 | Google Play ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/***/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

```

Library version: 6.0.0-alpha.6

## Steps To Reproduce

1. Navigate to / Open a screen with a Video
2. Start playing the video
3. Go back / Unmount Video component
4. Video is still running

## Expected behaviour

Video should stop and RCTVideo should be deinit

### PR DESCRIPTION
**Pull request by cguino**
#3166 Memory leaks
#3085 onFullscreen call backs are never fired
#3040 [Bug] Fullscreen broken on iOS due to #3017
#2744 Unblock the main thread while replacing the source ([cf comment](https://github.com/react-native-video/react-native-video/issues/2744#issuecomment-1219444287))

### CODE REVIEW

**Comment by freeboub** [comment]
thank for this PR, it looks good except https://github.com/react-native-video/react-native-video/issues/2744 Unblock the main thread while replacing the source (https://github.com/react-native-video/react-native-video/issues/2744#issuecomment-1219444287)

We already experiment this change, but it causes crash when fast changing source...
can you revert this change and I will merge this soon.

The good fix has be be discussed (I think I know the good fix but this is a big architecture change ...)

**Comment by cguino** [comment]
Thank you, I revert #2744

**Comment by marcel-happyfloat** [comment]
@freeboub the main thread blocking makes this library unusable for us in the real world with bad internet connection trying to scroll a feed of video items. Do you think the fix is safe to use for multiple video elements, with only one fixed source at a time? (or mounting/unmounting with new source). Thank you.
I really appreciate all your work, unfortunately I can't help debugging on the native side.

**Comment by Trashpants** [comment]
Also in the same boat with the blocking main thread, without knowing too much about the internals can we have this as an optional so additional prop such as dangerouslySwapIosVideoSource as a bool on the player component?

**Comment by freeboub** [comment]
I totally understand the issue of startup I revert following change: 1f27ffbc8101044eb59866886fec6fd12223febf
which was causing the crash. I really think it will cause the same issue.
This code also causes an issue when rapidly changing source...
There is clearly a concurrency issue in react native video.
I fixed it on android in my company fork but it is a nightmare to backport, I need to find time to reimplement it here.
moreover the PR of new arch will also conflict with it :/
Let see.
Notice that I advise you to patch the package (with patch-package) or create your own fork if you really want this change.
Personally I prefer latency than crash ...

**Pull request merged**
