### PR TITLE
reloadSource if repeat is set after paused

### PR DESCRIPTION
**Pull request by jalieven**
When the Exoplayer first receives the paused=false before it receives repeat=true in the current implementation the video will not get repeated. Since the LoopingMediaSource will get instantiated when paused is set (which calls startPlayback, which calls initializePlayer, which results in a non looping source). So simply reloadSource after the repeat prop is set fixes this issue.

### CODE REVIEW

**Comment by radko93** [comment]
Is this stopping a video if you change repeat prop while playing the video? I did a fix in #587 but it's a bit different. Maybe your PR is better if it does not have any side effects.

**Comment by jalieven** [comment]
I haven't tested the change of repeat yet with this PR. Can verify this on monday.

**Comment by jalieven** [comment]
@radko93 if you change the repeat prop while playing the video the video starts anew but plays once when repeat was changed to false and loops if it was changed to true. That is if you have the paused prop set to true

**Comment by jalieven** [comment]
@radko93 When I try your PR #587 and change the repeat to false (while playing the video) where it was first true, the video keeps on repeating. Have you tested this use-case?

**Comment by radko93** [comment]
@jalieven thanks for the feedback, I will try and fix that.

**Comment by jalieven** [comment]
Anyhow if this use-case works your PR looks nicer indeed. Mine is kinda brute-force.

**Comment by cobarx** [comment]
We no longer need to use a LoopingMediaSource since ExoPlayer added support for a repeat mode in 2.5.0. This is tested and working with the latest release.

**Pull request closed without merging**
