### PR TITLE
Fix volume reset issue in exoPlayer

### PR DESCRIPTION
**Pull request by justsml**
Fix max volume issue in exoPlayer when gaining focus.

See issue #2153

Credit: https://github.com/react-native-video/react-native-video/issues/2153#issuecomment-755354860

### CODE REVIEW

**Review by hueniverse — APPROVED** [review]

**Comment by hueniverse** [comment]
@freeboub Can you do a quick review?

**Review by freeboub — APPROVED** [review]

**Comment by freeboub** [comment]
Yes this is Great 👍

**Comment by MitoMonkey** [comment]
The fix works and I see it was merged in May 21, but it does not seem to be included in v5.2.x as can be seen here: https://github.com/react-native-video/react-native-video/blob/ce03223f94771153962285042f28bed8881d633c/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L1243

May I ask why?

**Comment by justsml** [comment]
It might have needed a fallback check to see if the `audioVolume == 0.f` then reset it to `1.f`.
Not sure.

**Comment by justsml** [comment]
Oh, never mind, it appears [lined up for the newest v6.](https://github.com/react-native-video/react-native-video/blob/2349fad25f402d75812d449e4630172851590dc6/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L1691)

**Pull request merged**
