### PR TITLE
feat(android) : add rtsp support

### PR DESCRIPTION
**Pull request by freeboub**
Enable RTSP support on android
Add sample url in basic sample

### CODE REVIEW

**Review by VMBindraban — APPROVED** [review]

**Comment by Michota** [comment]
Why this is not merged yet?

**Comment by VMBindraban** [comment]
@freeboub Can this be merged?

**Comment by freeboub** [comment]
@VMBindraban @Michota were you able to test this PR successfully?

**Comment by VMBindraban** [comment]
@freeboub I am getting a back screen when i try to load `rtsp://rtspstream:540f2c810f3a4d8e6ed952c2f3281a@zephyr.rtsp.stream/movie` (made the url invalid due 2 GB bandwidth limitation)

```
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal: Playback error
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:205)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:294)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:418)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:311)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1006)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
04-15 11:47:06.781  5819  6072 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1012)
```

Plays fine in VLC.

**Comment by freeboub** [comment]
@VMBindraban ok, it explains why it is not merged. Can you explain how you setup your sample stream please ? Last time I tried i wasn't able to setup vlc as rtsp stream server... (I have lost my notes on my initial test)

**Comment by VMBindraban** [comment]
I am using a free RTSP stream service: https://rtsp.stream/

**Comment by freeboub** [comment]
Ok thank you for the sample stream, I was able to test it successfully and add a sample stream in demo app, let continue in:  https://github.com/react-native-video/react-native-video/pull/3677

**Pull request closed without merging**
