### PR TITLE
Fix issues with notification observer management

### LINKED ISSUE #60: Restarting once video has ended
Hi,

is there currently a possibility to restart the video / audio, once it has finished? I can't see anything about it in the example / docs.

Thanks :)
Philipp

### LINKED ISSUE #61: onEnd is not called
Hi,

onEnd seems not to get called when playing from an URL:

``` javascript
                        <Video source={{uri: ITUNES_JSON.previewUrl}} // Can be a URL or a local file.
                           rate={1.0}                   // 0 is paused, 1 is normal.
                           volume={1.0}                 // 0 is muted, 1 is normal.
                           muted={false}                // Mutes the audio entirely.
                           paused={!this.state.itunesPlaying}               // Pauses playback entirely.
                           resizeMode="cover"           // Fill the whole screen at aspect ratio.
                           repeat={false}                // Repeat forever.
                           onEnd={() => {console.log('test');}}/>
```

with the following URL:

``` javascript
  "previewUrl":"http://a1471.phobos.apple.com/us/r2000/004/Music/ec/88/d0/mzm.fqrwrunh.aac.p.m4a",
```

Any idea?

### PR DESCRIPTION
**Pull request by isair**
Fixes #61
Fixes #60

### CODE REVIEW

**Comment by isair** [comment]
@brentvatne The only remaining problem is that the removeObserver call in `setRepeatDisabled` also removes the observer set for firing the `onEnd` event.

**Comment by isair** [comment]
@brentvatne Let me know what you think about 0e944d0. Basically, I merged the two AVPlayerItemDidPlayToEndTimeNotification handlers into a single method to fix the problem.

**Comment by brentvatne** [comment]
Looks good to me! I tried it on the example project and it worked as expected, code looks good (these are unfortunately the only "tests" I have in place for this project) squashed into one commit and merged!

44b17119dd1480e85898e358e45376c2a0eae61e

Also, I really appreciate your help so I gave you a commit bit - you'll see that you're now a "Collaborator" :smile: :tada: :balloon:

**Comment by isair** [comment]
Ah, no problem. Thanks!

**Pull request closed without merging**
