### PR TITLE
docs: update platforms in properties tab

### PR DESCRIPTION
**Pull request by DominikDanielewicz**
## Summary
Update the platform compatibility in properties. 

### Changes
Created the component for displaying platforms in mdx file.

### CODE REVIEW

**Comment by freeboub** [comment]
This branch has conflicts that must be resolved ...

**Comment by KrzysztofMoch** [comment]
Hey @DominikDanielewicz, how about we add this also to: DRM, Events, Methods 😄

**Comment by DominikDanielewicz** [comment]
> Hey @DominikDanielewicz, how about we add this also to: DRM, Events, Methods 😄

Hey @KrzysztofMoch, just updated platforms inside DRM, Events and Methods tab

**Review by freeboub — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]
@DominikDanielewicz Thanks!

**Pull request merged**
