### PR TITLE
fix: use AVPlayerLooper to repeat videos on iOS

### PR DESCRIPTION
**Pull request by leethree**
The original `repeat` implementation on iOS leaks memory for some reason and it will cause app to become slower and slower each time it loops. This PR replace the implementation with [AVPlayerLooper](https://developer.apple.com/documentation/avfoundation/avplayerlooper) which would solve the issue.

This PR is based on #1787.

### CODE REVIEW

**Comment by FansPro** [comment]
Has this merge to master ? I have repeat video on ios, it get slower and slower..

**Comment by adamkoch** [comment]
I was running into this memory leak and this PR seems to fix things. However, it seemed to cause another issue. In my app, I display up to 8 videos at the same time (all looping). After this patch, a random number of those would just render empty/blank. I'm not familiar with Objective C and iOS development but after commenting out this line it seems to have fixed it for me:
https://github.com/react-native-community/react-native-video/pull/1799/files#diff-42e8804735be64e84d6dd1fb103210a1R379

I'm guessing some sort of race condition with how _playerLooper is set but I couldn't work out exactly how or why.

**Comment by leethree** [comment]
@adamkoch thanks for testing out! I think removing the line would cause a problem if `source` is changed for the component. But I haven't been able to figure out how to properly handle it. Would be great if someone more proficient in Objective C could help out 😀

**Comment by jayasme** [comment]
@adamkoch  Hi, can you please print what `_playerItem` is before `_player = [AVQueuePlayer playerWithPlayerItem:_playerItem];`?
And also check `status` & `error` properties of `_playerLooper` after it has been initialized.

**Comment by adamkoch** [comment]
@jayasme 

> can you please print what _playerItem is before _player = [AVQueuePlayer playerWithPlayerItem:_playerItem];

I just did a NSLog directly before this and it shows:
2019-12-20 16:28:37.827398+1100 MyApp-tvOS[13667:125228] _playerItem = <AVPlayerItem: 0x6000000b3f80, asset = <AVURLAsset: 0x60000035fac0, URL = file:////Users/adam/Library/Developer/CoreSimulator/Devices/F0C8BC28-3E5D-4F9A-9172-03357ACE393C/data/Containers/Data/Application/8C499507-2CEE-454B-982F-3B660831FC69/Library/Caches/test.mp4>>

When I load 8 videos on the screen and some show and some don't, they all print out a similar object (different values but valid object).

> And also check status & error properties of _playerLooper after it has been initialized.

I did a NSLog of success/status directly after _playerLooper is initialized (there's 2 locations in the file) but in both cases the values are always null. I'm not sure if maybe those values are populated asynchronously so if printing immediately after they are not yet populated?

**Comment by jayasme** [comment]
> @jayasme
> 
> > can you please print what _playerItem is before _player = [AVQueuePlayer playerWithPlayerItem:_playerItem];
> 
> I just did a NSLog directly before this and it shows:
> 2019-12-20 16:28:37.827398+1100 MyApp-tvOS[13667:125228] _playerItem = <AVPlayerItem: 0x6000000b3f80, asset = <AVURLAsset: 0x60000035fac0, URL = file:////Users/adam/Library/Developer/CoreSimulator/Devices/F0C8BC28-3E5D-4F9A-9172-03357ACE393C/data/Containers/Data/Application/8C499507-2CEE-454B-982F-3B660831FC69/Library/Caches/test.mp4>>
> 
> When I load 8 videos on the screen and some show and some don't, they all print out a similar object (different values but valid object).
> 
> > And also check status & error properties of _playerLooper after it has been initialized.
> 
> I did a NSLog of success/status directly after _playerLooper is initialized (there's 2 locations in the file) but in both cases the values are always null. I'm not sure if maybe those values are populated asynchronously so if printing immediately after they are not yet populated?

status & error will not be set asynchronously at least by my understanding according to Apple's document, I don't know if you could try to make all players link the same one playerItem to see if can load all or part.

**Comment by ninjz** [comment]
Any updates on the status of this?

**Comment by pribeh** [comment]
Any reason why this wasn't merged? This resolves the issue for us.

**Comment by adamkoch** [comment]
FWIW, this is still an issue for me.

**Comment by hueniverse** [comment]
@leethree Can you please rebase so I can merge your fix?

**Pull request closed without merging**
