### PR TITLE
Removed JS fullscreening for Android

### PR DESCRIPTION
**Pull request by jensellfors**
This reverts this PR: https://github.com/react-native-community/react-native-video/pull/1730

If we implement fullscreen for Android it should be done properly. I suggest we look at how Expo are doing it. The quality of this JS implementation is not something we want in the code library.

### CODE REVIEW

**Comment by jensellfors** [comment]
This reverts https://github.com/react-native-community/react-native-video/pull/1730

**Comment by florinlazau** [comment]
@jenshandersson, are there any plans for implementing Android full-screen support?

**Comment by jensellfors** [comment]
If it's a popular request I'm sure someone will help out and build it. But when we add it we should do it natively and properly. We can look at Expo or maybe this one that was top of google: https://medium.com/@danyalstd/adding-a-fullscreen-button-to-exoplayer-87f685279cae

**Comment by 349989153** [comment]
@jenshandersson what about this PR?

https://github.com/react-native-community/react-native-video/pull/2073

**Pull request merged**
