### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by ghost**
Add required step to the installation instructions after hitting the same problem from #1. Also removes a duplicate data property.

### CODE REVIEW

**Comment by brentvatne** [comment]
@jhabdas - Thanks! This should help people getting going with it :smile:

**Comment by ghost** [comment]
Glad I could help. Mind tagging a `0.3.6` release and updating NPM? I'm [currently forked](https://github.com/jhabdas/react-native-es6-reflux/blob/master/package.json#L11) due to build issues with Webpack and the dupe data property bugfix I snuck in with the doc updates.

**Comment by ghost** [comment]
Works great by the way! https://t.co/9XsWA4sgWb

**Comment by brentvatne** [comment]
@jhabdas - thanks, bumped to 0.3.6 and pushed!

**Comment by brentvatne** [comment]
@jhabdas - also, awesome to see it in use! :smile:

**Pull request merged**
