### PR TITLE
feat: yarn 3 support

### PR DESCRIPTION
**Pull request by yungblud**
## Summary
- bumped up root package manager (yarn version) to 3.6.4 which is suggested version from react-native.

### Motivation
- Wanted to bump up yarn version with same version as react-native is suggesting.
- From react native upgrade helper web site, you can find out packageManager
  - https://react-native-community.github.io/upgrade-helper/?from=0.73.6&to=0.76.0-rc.4
  - https://react-native-community.github.io/upgrade-helper/?from=0.73.6&to=0.76.0-rc.4#RnDiffApp-package.json

### Changes
- added .yarnrc.yml
- modified .gitignore for yarn files

## Test plan

### CODE REVIEW

**Comment by yungblud** [comment]
Having an issue with "yarn install" and "yarn.lock" in `examples` project such as "examples/bare"
Have a look this issue. https://github.com/TheWidlarzGroup/react-native-video/issues/4250

**Comment by freeboub** [comment]
I confirm that my project also uses yarn 3 without any issue (but not yet react native 0.76)

**Comment by KrzysztofMoch** [comment]
@yungblud I have made PR that change packageManager to [bun](https://bun.sh/) and change our repo structure to monorepo https://github.com/TheWidlarzGroup/react-native-video/pull/4255

**Comment by yungblud** [comment]
> @yungblud I have made PR that change packageManager to [bun](https://bun.sh/) and change our repo structure to monorepo #4255

@KrzysztofMoch Cool! It seems pretty nice!
I will close this PR as your PR #4255 does similar stuffs alternatively.

**Pull request closed without merging**
