### PR TITLE
Support react-native > 0.40

### PR DESCRIPTION
**Pull request by olofd**
Updated header imports to build on react-native > 0.40

### CODE REVIEW

**Comment by hellogerard** [comment]
Consider bumping the package version to 1.0, since it is a breaking change (react-native-video will no longer work on React Native <= 0.39).

**Comment by olofd** [comment]
Bumped version. Let me know if there is anything else I can do.

**Comment by joekim** [comment]
Are you guys having issues with the device events such as, onLoad, not triggering RN .40?

**Comment by olofd** [comment]
@joekim yup.. same here. This PR was intended just to make it build. But can take a look at this as well.

**Comment by olofd** [comment]
@joekim No, wait. It worked here. Just some confusing JS. The event is `onLoad` not `onVideoLoad`. When I called it `onLoad` it was called.

**Comment by joekim** [comment]
@olofd My onLoad does not seem to be triggering. But, I know through the debugger that onVideoLoad is being emitted on the native side. How does that event name map to onLoad? Any tips on debugging my issue?

**Comment by olofd** [comment]
set a `debugger;` on line 48 in Video.js in your node_modules/react-native-video folder, close the packager-terminal and relaunch. Mine hit that then ran onLoad={() => console.log('load')} on the video element at least. onVideoLoad is mapped to onLoad in JS: onVideoLoad: this._onLoad (Line 169).

**Comment by joekim** [comment]
@olofd I added a breakpoint in _onLoad and it's not triggering. I added one in render just to see that it's working and that works fine. I also know that onVideoLoad is being emitted by native. Not sure what the issue is. Maybe it's something to do with my project. I'm going to try to create a new project from scratch.

**Comment by hellogerard** [comment]
> Are you guys having issues with the device events such as, onLoad, not triggering RN .40?

To test this, I tried to see if the Example project would work using this PR branch. I couldn't even get it to build (this issue, I believe: https://github.com/facebook/react-native/issues/11721). I tried upgrading RN a few different ways with the same result.

Can anyone get the Example project working in RN 0.40?  If we can get the native files upgraded, we could add that to this PR.

**Comment by olofd** [comment]
@hellogerard I'll take a look at the example-project tonight.

**Comment by olofd** [comment]
@hellogerard I've now upgraded the example project to run on 0.40. Ran `react-native upgrade` and did some manual fixes after that. Now runs. Also left a console.log for you and @joekim in `onLoad`. Would recommend that you wipe your node_module-folder in the example project and run npm install in the example project again after pulling my update.

**Comment by hellogerard** [comment]
@olofd That's awesome. No reason not to merge this now.

@joekim If you are still having issues with callbacks, I suggest creating a new issue. (BTW, is your video playing at all? If not, make sure you are using a `https` URL.)

**Comment by joekim** [comment]
@hellogerard I'll take a look. The video is playing but the call backs are triggering.

**Comment by joekim** [comment]
@olofd @hellogerard I retested the sample app and it triggers properly.

**Comment by chirag04** [comment]
@mattapperson This PR is merged but react-native-video v1.0 is not published on npm. Can you also publish the latest master on npm.

**Comment by mattapperson** [comment]
published

**Pull request merged**
