### PR TITLE
feat: remove typescript

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary
Today is a great day to make step forward and remove typescript

### Motivation
Make some fun

### Changes
- removed Typescript

## Test plan
None, lets yolo merge

PS: it's joke pls no merge 😅

### CODE REVIEW

**Comment by freeboub** [comment]
😵‍💫🎁💣

**Comment by freeboub** [comment]
Did you test it with react native 0.23 ?

**Comment by KrzysztofMoch** [comment]
Ofc! also made sure that it is compatible with Flutter 🙌

**Comment by nicolaosm** [comment]
Thanks for making it work with react native 0.23 @KrzysztofMoch @freeboub ! Hope to see RN 0.16 support soon

**Comment by KrzysztofMoch** [comment]
No problem but we better leave TypeScript for our sake 😅

**Pull request closed without merging**
