### PR TITLE
Allows custom exoplayer Version

### PR DESCRIPTION
**Pull request by sidferreira**
This is one of the many changes I had to do to handle delegates

### CODE REVIEW

**Comment by harshaliitr** [comment]
This PR is incomplete. According to docs you should not mismatch versions of exoplayer and exoplayer:extension-okhttp.

you need to update the following lines as well - 

`implementation('com.google.android.exoplayer:extension-okhttp:2.13.2') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }`

**Comment by hueniverse** [comment]
@sidferreira I don't see the feedback from @harshaliitr addressed in the PR. Is this still needed?

**Comment by sidferreira** [comment]
@hueniverse we use it

**Comment by hueniverse** [comment]
Thanks for getting back to me. What about the review comment from @harshaliitr? It will also require rebasing.

**Pull request closed without merging**
