### PR TITLE
[ios] Display fullscreen video with controls enabled

### LINKED ISSUE #1568: iOS Fullscreen with Controls Crash
@ashnfb @cobarx 
### Current behavior
The following change crashes our current implementation on iOS:
https://github.com/react-native-community/react-native-video/pull/1441/files#diff-42e8804735be64e84d6dd1fb103210a1R566
We display the video in full screen as soon as it is loaded.
After updating this implementation crashes.
A fix is not urgent for us, as we do not need the controls in non fullscreen mode on iOS.
As a workaround we just disable the controls on iOS, which resolves the issue.

### Reproduction steps
`<Video
          source={this.props.source}
          resizeMode='contain'
          paused={false}
          repeat={false}
          controls={true}
          onLoad={() => this.player && this.player.presentFullscreenPlayer()}
          ref={this.handleRef}
          style={fullscreen}
        />`

Additional info: We render the video in a react navigation dialog.

### Expected behavior
It does not crash.

### Platform
* iOS

```
Exception thrown while executing UI block: Application tried to present modally an active controller <XXX.ReactNativeViewController: 0x7ff09b6182c0>.

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1112
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.461
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

### PR DESCRIPTION
**Pull request by r0b0t3d**
Fix #1568 
Allow video display in fullscreen with controls enabled

### CODE REVIEW

**Review by axelpey — APPROVED** [review]

**Comment by VanTigranyan** [comment]
Hi everyone. When this can be merged?

**Comment by eyalabadi98** [comment]
Any update?

**Comment by joeyscarim** [comment]
would also like this merged

**Comment by stefansurkamp** [comment]
Any update on this? Would be pretty important for our application.

**Comment by juancarlosqr** [comment]
@cobarx @licks92 any notion when this could be merged? 🙏🏼

**Comment by ericlifs** [comment]
@r0b0t3d any news in merging this into master? It's really very relevant 👍

**Comment by r0b0t3d** [comment]
@ericlifs I don't have permission to merge this. If you all want this, you can help to test and make sure it is ok. So that it can easier to reach out to the maintainers 😅

**Comment by ahanusek** [comment]
@r0b0t3d 

Can you help with this file conflict in RCTVideo.m? I've tried to do this on my own but unfortunately without good results :D.

**Pull request closed without merging**
