### PR TITLE
Add controls property to Android

### LINKED ISSUE #120: [Android] Support `controls` property
As seen in #119, but for Android.

### PR DESCRIPTION
**Pull request by Vunovati**
- displays MediaController over the Video screen if enabled

Implements native controls on Android in the same fashion as #119 
Fix #120 #221

### CODE REVIEW

**Comment by zmuqzmuq** [comment]
@Vunovati  hi, in my android project, I set controls to 'true',but still don't have controls in Video. What's wrong? Thanks!

**Comment by flexdhana** [comment]
screen shot 2016-09-13 at 4 37 55 pm

Nice one, its displaying controls over the video, but its missing fullscreen button.
i used Android (6 - Marshmallow) emulator. please advise me.. thanks

**Comment by muvv** [comment]
Can i get example of implementing controls in android
i added controls={true} prop ,but i am not getting control options in android. It could be better if i can get a example in android

**Comment by santomegonzalo** [comment]
@muvv did you fix it to show the controls? Im doing the same as you and its not working

**Comment by ZeroCool00** [comment]
@muvv  any luck yet?
@Vunovati  control not showing on android

**Pull request merged**
