### PR TITLE
Bugfix/android disablefocus audio

### PR DESCRIPTION
**Pull request by KurtMakesWeb**
#### Provide an example of how to test the change
Test by playing music from a different app. Letting it play in the background, and open your app with different videos set to "disableFocus" true and false on different views in your app on an Android device. You will notice that the videos with true will allow the background music to play, while the ones set to false will stop the background music.

#### Describe the changes
This PR makes it so the requestAudioFocus method never gets called before the props get set from the react native component. I noticed that the disableFocus was false at first and would change to true, so I thought it best to also stop it if there was no srcUri as well.

### CODE REVIEW

**Comment by marinobresciani** [comment]
I warmly welcome this PR, and I hope it gets merged soon. :)

**Review by adrianomarquess — APPROVED** [review]

**Comment by igor-pol** [comment]
What's the current status on this?

**Comment by gusy126** [comment]
Since this still needs to be merged, I just wanted to also confirm that I was having the same issue with the disableFocus prop and this got it working.

**Comment by OlivierFreyssinet-old** [comment]
This works exactly as expected 👌

**Comment by ouabing** [comment]
I can confirm this fixed my issue. It's really annoying stopping other app's sound when start app(my app has a landing video).

**Comment by pouyaemami** [comment]
I can also confirm that this fixes the issue on Android. Can this please be merged and added to the next release?

**Comment by agmcleod** [comment]
It would be great if this could get merged, would avoid me needing to fork it :). Thanks RN Community team!

**Review by CHaNGeTe — APPROVED** [review]

**Comment by CHaNGeTe** [comment]
For me it is approved, so a good candidate for next release.

**Review by n1ru4l — APPROVED** [review]

**Comment by pouyaemami** [comment]
Hey @KurtMakesWeb just wanted to thank you for putting in this fix and if it's not too much to ask: could you please resolve the merge conflicts so that it can me merged? I'm working on a project that needs this and I would rather not have to create a fork for this purpose alone.

**Comment by CHaNGeTe** [comment]
related: https://github.com/react-native-community/react-native-video/issues/1462#issuecomment-504999168

**Comment by KurtMakesWeb** [comment]
@pouyaemami I've fixed the merge conflicts. All should be good now

**Pull request merged**
