### PR TITLE
Reduce package size

### PR DESCRIPTION
**Pull request by retyui**

### CODE REVIEW

**Comment by retyui** [comment]
### On PR branch
```bash
npm pack 

#npm notice package size:  74.7 kB                                 
#npm notice unpacked size: 332.0 kB  
```

### On master branch
```bash
npm pack

#npm notice package size:  344.5 kB                                
#npm notice unpacked size: 660.1 kB    
```

**Comment by cobarx** [comment]
Thanks for contributing this!

**Comment by retyui** [comment]
@cobarx 
Why did you close this PR without a merger?

**Comment by cobarx** [comment]
Oops had meant to merge this and hit close by accident. Sorry about that.

**Pull request merged**
