### PR TITLE
[ExoPlayer] Load new source if it is different

### PR DESCRIPTION
**Pull request by AndrewJack**
Fixes: #481 

Try with these test streams
```javascript
const YT_GLASS_SOURCE = { uri: 'http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0', type: 'mpd' };
const YT_GPLAY_SOURCE = { uri: 'http://www.youtube.com/api/manifest/dash/id/3aa39fa2cc27967f/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=A2716F75795F5D2AF0E88962FFCD10DB79384F29.84308FF04844498CE6FBCE4731507882B8307798&key=ik0', type: 'mpd' };

```

### CODE REVIEW

**Comment by darbaoui** [comment]
@AndrewJack  
this update #502 cannot allow to play audio in background.
--back to home not audio playing in background
-- return to the app again, audio continue to  playing

**Comment by onehassan** [comment]
How can I apply the fix in my react-native project, i tried to replicate the changes in the source code of the exoplayer node-module but the issue still persists?

**Comment by onehassan** [comment]
I think I found the issue, I have a background Video on the Login screen and another instance in another screen that I push on top with a stack navigator, It seems that the first instance of the video overlaps the other instance. How can I handle such scenario?

**Comment by renay007** [comment]
I am having the same issue on Android.

**Pull request merged**
