### PR TITLE
Better support newer versions of RNW (64 and newer)

### PR DESCRIPTION
**Pull request by namrog84**
React-Native-Windows deprecated arm 32 bit as it was generally unused and untested as of ReactNativeWindows 64. RN is now on 66 and soon to be on 67.  It should be removed to prevent any unnecessary work into a deprecated and unsupported path. Arm64 is still supported scenario. 

Somewhere around RNW64 or 65, some things changed with UIManager, where it becomes a TurboModule in release builds, but is still a NativeModule in debug builds. This is a challenging issue to diagnose..
This caused an issue with how UIManager was being accessed in RNV. Updated the way to access to better support all scenarios. We have been using this change as a patch-package in our android/ios/windows app for 6+ months without issue.

Question:
Should I update package.json and changelog to be -alpha1? 

https://microsoft.github.io/react-native-windows/blog/2021/03/16/64updates

### CODE REVIEW

**Comment by jeanmaried** [comment]
Any update on getting this merged?

**Comment by adamgorMSFT** [comment]
I would love to get this merged, who can approve/merge it?

@asklar can you review/approve?

**Review by asklar — APPROVED** [review]
lgtm

**Comment by namrog84** [comment]
@asklar  do you have permission to 'complete/merge' this PR?   or who do I need to ping to get that done? 

I don't have permission to complete this PR.

`Only those with [write access] to this repository can merge pull requests`

**Comment by asklar** [comment]
@isair it looks like you might have write access, would you be able to complete this PR? Thanks!

**Comment by namrog84** [comment]
@hueniverse  I know I still need to rally more support for long term support of windows. But in the mean time, can this PR get approved/merged?  

We've been using a patch-package applying these same changes in multiple apps for last 6+ months without issue.

**Comment by hueniverse** [comment]
Looks like this overlaps with https://github.com/react-native-video/react-native-video/pull/2296 where the main question I had was if it will break Windows. Sounds like it will fix it.

**Pull request merged**
