### PR TITLE
introducing onExternalPlaybackChange

### PR DESCRIPTION
**Pull request by arturjaworski**
adds possiblity to get `AVPlayer.externalPlaybackActive` flag

### CODE REVIEW

**Comment by cobarx** [comment]
Hi @arturjaworski, this looks great and appears to being pretty close to being ready to merge.

Can you document this in the README file including what the event payload looks like and also provide instructions on how to test this. I'm ordering an Apple TV for testing which should arrive late next week where I can test this.

**Comment by arturjaworski** [comment]
@cobarx updated :)

**Comment by cobarx** [comment]
What do I need to do to test this, I'm not too familiar with doing external playback.

**Comment by arturjaworski** [comment]
Please try to connect/disconnect to AirPlay. Some AirPlay server should be enough (eg. Reflector 3). `onExternalPlaybackChange` will be called on connection/disconnection. Just let me know if you'll have any problem! :)

**Comment by cobarx** [comment]
Tested this with my new AppleTV and it worked great. Thanks!

**Pull request merged**
