### PR TITLE
Android support

### LINKED ISSUE #91: Android Support
Am interested to see if this can be set up to work on android also. 
Had a look at the existing code and had some queries though.

`libRCTVideo.a` step - is this also necessary to get it to work on android?
`RCTVideo.h, RCTVideo.m, RCTVideoManager.h, RCTVideoManager.m` - these are objective C stuff so i'm guessing an equivalent android native code for media must also be added?

### LINKED ISSUE #94: onVideoError and onVideoLoadStart native properties are unset
It looks like the `onVideoError` and `onVideoLoadStart` properties are not being [set as nativeProps](https://github.com/brentvatne/react-native-video/blob/3aa46875a58b857861377dc1528088ae027627e2/Video.ios.js#L83-L95).

Should they be set to `this._onError` and `this._onLoadStart`?

### PR DESCRIPTION
**Pull request by isair**
- [x] Add Android support.
- [x] Update README.
- [x] Update example project.

Closes #91, fixes #94.

[Review on Reviewable](https://reviewable.io/reviews/brentvatne/react-native-video/103)

### CODE REVIEW

**Comment by jforaker** [comment]
@isair could you provide a gist or readme on installation instructions? I recognize the risk on my end, but i would be eternally grateful as time is of the essence and i really need this :)

**Comment by isair** [comment]
@jforaker You need to make additions to 3 files in your react-native project.

## android/settings.gradle

```
include ':RCTVideo', ':app'
project(':RCTVideo').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

## android/app/build.gradle

```
dependencies {
   ...
   compile project(':RCTVideo')
}
```

## MainActivity.java

On top, where imports are:

``` java
import com.brentvatne.react.ReactVideoPackage;
```

Under `.addPackage(new MainReactPackage())`:

``` java
.addPackage(new ReactVideoPackage())
```

**Comment by jforaker** [comment]
Thanks! 

Howerver, I think you forgot `ReactVideoView` in your package.json.  I fixed that, however i get red death screen error on run:

`Requiring unknown module "keymirror"`

I did npm install keymirror and that did not help. Ideas?

**Comment by jforaker** [comment]
@isair After testing a few times, few different configs, the video does not play, and i keep getting this error in Android Studio (no errors in chrome):

```
11-16 19:53:44.255 2415-2415/com.crashr_react_native W/ResourceType: No package identifier when getting value for resource number 0x00000000
11-16 19:53:44.255 2415-2415/com.crashr_react_native W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.content.res.Resources.getValue(Resources.java:1266)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.content.res.Resources.openRawResourceFd(Resources.java:1224)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.yqritc.scalablevideoview.ScalableVideoView.setRawData(ScalableVideoView.java:121)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:119)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:66)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.ViewManagersPropertyCache$MapPropSetter.updateProperty(ViewManagersPropertyCache.java:175)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateProp(ViewManagersPropertyCache.java:63)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:182)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:137)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:574)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:622)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:114)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:549)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.os.Looper.loop(Looper.java:135)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-16 19:53:44.259 2415-2415/com.crashr_react_native W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I have the "broadchurch.mp4" in the same directory as my video component, calling it like this:

```
    <Video source={{uri: 'broadchurch'}}
           style={styles.fullScreen}
           rate={this.state.rate}
           paused={this.state.paused}
           volume={this.state.volume}
           muted={this.state.muted}
           resizeMode={this.state.resizeMode}
           onLoad={this.onLoad}
           onProgress={this.onProgress}
           repeat={false}/>
```

Does it work for you? Am I setting the source incorrectly?  (tried new `source={require('./my-icon.png')}` style syntax and that threw a red screen error)

**Comment by isair** [comment]
@jforaker Try putting your video file in your Android raw sources folder.

**Comment by jforaker** [comment]
Ok I tried all of these:
`<Video source={{uri: './android/app/src/main/assets/broadchurch'}}`
`<Video source={{uri: './android/app/src/main/assets/broadchurch.mp4'}}`
`<Video source={{uri: 'android/app/src/main/assets/broadchurch'}}`
`<Video source={{uri: 'android/app/src/main/assets/broadchurch.mp4'}}`

 and get the same error

```
11-16 20:58:03.066 21349-21349/com.crashr_react_native W/System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0
```

Also tried a youtube source and get this:

```
11-16 20:53:26.010 19736-19736/com.crashr_react_native W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
11-16 20:53:26.024 2551-15396/? D/NuPlayerDriver: reset(0xf10cfae0)
11-16 20:53:26.024 2551-15396/? D/NuPlayerDriver: notifyListener_l(0xf10cfae0), (1, 0, 0)
11-16 20:53:26.024 2551-15396/? D/NuPlayerDriver: notifyListener_l(0xf10cfae0), (8, 0, 0)
11-16 20:53:26.024 2551-20102/? D/NuPlayerDriver: notifyResetComplete(0xf10cfae0)
11-16 20:53:26.025 2551-4928/? D/NuPlayerDriver: reset(0xf10cfae0)
11-16 20:53:26.041 19736-19736/com.crashr_react_native W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
11-16 20:53:26.041 2551-20107/? D/NuPlayer: onSetVideoSurface(0xee403500, no video decoder)
11-16 20:53:26.990 2551-20126/? I/NuCachedSource2: caching reached eos.
11-16 20:53:27.003 2551-20127/? E/NuCachedSource2: source returned error -1, 10 retries left
11-16 20:53:27.027 2551-20108/? E/GenericSource: Failed to init from data source!
11-16 20:53:27.028 2551-20107/? D/NuPlayerDriver: notifyListener_l(0xf10d0260), (100, 1, -2147483648)
11-16 20:53:27.028 19736-20106/com.crashr_react_native E/MediaPlayer: error (1, -2147483648)
11-16 20:53:27.032 19736-19736/com.crashr_react_native E/MediaPlayer: Error (1,-2147483648)
11-16 20:53:28.865 3674-12188/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=539731960, 192.168.0.1, [407009528617], RTM_NEWNEIGH, NUD_STALE}
11-16 20:53:30.272 2551-20127/? I/NuCachedSource2: retrying a previously failed read succeeded.
11-16 20:53:30.276 2551-20127/? I/NuCachedSource2: caching reached eos.
11-16 20:53:30.282 2551-20103/? E/GenericSource: Failed to init from data source!
11-16 20:53:30.290 2551-20103/? W/AMessage: failed to post message as target looper for handler 0 is gone.
```

**Comment by isair** [comment]
`<Video source={{uri: 'broadchurch'}} />` is fine. Just put that mp4 file in `android/app/src/main/res/raw/`.

**Comment by jforaker** [comment]
BOOM goes the dynamite! There it is!! :+1:   thank you

**Comment by jforaker** [comment]
Be sure to make a note in the install docs:

```
Error: 'G' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
111
```

aka filename must only contain lowercase a-z, 0-9, or underscore

**Comment by isair** [comment]
@jforaker Will keep in mind, cheers!

**Comment by isair** [comment]
Reviewed 8 of 11 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/brentvatne/react-native-video/103)_

**Comment by brentvatne** [comment]
:heart_eyes:

**Comment by jforaker** [comment]
@isair it seems to be broken in 0.16.0 (was working flawlessly in 0.15 and under).  Possibly related to https://github.com/facebook/react-native/issues/4605  < check it out

**Comment by brentvatne** [comment]
@isair - this is working great so far! @jforaker - submitted a PR upstream to fix this. Also added the example project so I checked that off above. If you want to add the documentation above to the README (follow the steps verbatim and it worked without a hitch) I'm comfortable landing this now if you are!

**Comment by isair** [comment]
@brentvatne Thanks for fixing that issue. I'll update the README and finalize this PR tonight.

**Comment by brentvatne** [comment]
@jforaker - I would argue that @isair rocks more for his awesome work on this branch :rocket: :guitar:

**Comment by isair** [comment]
Reviewed 26 of 32 files at r3, 1 of 1 files at r4, 2 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/brentvatne/react-native-video/103)_

**Comment by isair** [comment]
@brentvatne Haha, my pleasure.

**Comment by rclai** [comment]
Whoa, this looks awesome. Is this about to get merged today?

**Comment by eranbes** [comment]
Yes, merge merge merge :-)

**Pull request merged**
