### PR TITLE
Issue 214

### LINKED ISSUE #214: Crash when changing the source
I want to set the source (a uri) from value on my component's state. The video loads correctly the source on the initial state, but whenever I change it, the whole app crashes. 
These are the logs from Xcode:
`2016-05-12 19:21:06.098 exponess[84835:1603400] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fbd2b504c40 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fbd28f49900> (
<NSKeyValueObservance 0x7fbd28fb72b0: Observer: 0x7fbd2b4e8710, Key path: rate, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fbd28fb6c10>
)'
*** First throw call stack:
(
    0   CoreFoundation                      0x0000000107c5ad85 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000106ab3deb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000107c5acbd +[NSException raise:format:] + 205
    3   Foundation                          0x00000001066c2d41 NSKVODeallocate + 294
    4   libobjc.A.dylib                     0x0000000106ac7afe _ZN11objc_object17sidetable_releaseEb + 232
    5   libsystem_blocks.dylib              0x000000010b8b26b1 _Block_release + 128
    6   libdispatch.dylib                   0x000000010b83b3eb _dispatch_client_callout + 8
    7   libdispatch.dylib                   0x000000010b8231ef _dispatch_main_queue_callback_4CF + 1738
    8   CoreFoundation                      0x0000000107bb40f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    9   CoreFoundation                      0x0000000107b75b99 __CFRunLoopRun + 2073
    10  CoreFoundation                      0x0000000107b750f8 CFRunLoopRunSpecific + 488
    11  GraphicsServices                    0x000000010c953ad2 GSEventRunModal + 161
    12  UIKit                               0x0000000109b57f09 UIApplicationMain + 171
    13  exponess                            0x000000010631f04f main + 111
    14  libdyld.dylib                       0x000000010b86f92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

### PR DESCRIPTION
**Pull request by sjchmiela**
Fixes #214

### CODE REVIEW

**Comment by stereodenis** [comment]
try this, got

```
Error setting property 'src' of RCTVideo with tag #14: Exception thrown while executing UI block: Cannot remove an observer <RCTVideo 0x7dc975b0> for the key path "rate" from <AVPlayer 0x7afd6780> because it is not registered as an observer.
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7b3d5fe0 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7b307ef0> (
<NSKeyValueObservance 0x7dcc2a80: Observer: 0x7dc975b0, Key path: rate, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7dcc2640>
)'
*** First throw call stack:
(
    0   CoreFoundation                      0x01a32494 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x008c0e02 objc_exception_throw + 50
    2   CoreFoundation                      0x01a323bd +[NSException raise:format:] + 141
    3   Foundation                          0x004f9097 NSKVODeallocate + 353
    4   libobjc.A.dylib                     0x008d4060 _ZN11objc_object17sidetable_releaseEb + 238
    5   libobjc.A.dylib                     0x008d5320 -[NSObject release] + 25
    6   AVFoundation                        0x00cec9df -[AVPlayerLayer dealloc] + 186
    7   Foundation                          0x004f8fa6 NSKVODeallocate + 112
    8   QuartzCore                          0x03868977 -[CALayer _dealloc] + 33
    9   QuartzCore                          0x038656a7 CALayerRelease + 110
    10  libobjc.A.dylib                     0x008d334f objc_release + 47
    11  AVFoundation                        0x00cee533 __destroy_helper_block_344 + 29
    12  libsystem_blocks.dylib              0x0585d9d0 _Block_release + 142
    13  libdispatch.dylib                   0x057ef9cd _dispatch_client_callout + 14
    14  libdispatch.dylib                   0x057d4f7c _dispatch_main_queue_callback_4CF + 910
    15  CoreFoundation                      0x0197c1be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
    16  CoreFoundation                      0x0193a434 __CFRunLoopRun + 2356
    17  CoreFoundation                      0x01939846 CFRunLoopRunSpecific + 470
    18  CoreFoundation                      0x0193965b CFRunLoopRunInMode + 123
    19  GraphicsServices                    0x0692c664 GSEventRunModal + 192
    20  GraphicsServices                    0x0692c4a1 GSEventRun + 104
    21  UIKit                               0x03b87eb9 UIApplicationMain + 160
    22  WTCC Premium TV                     0x0005a4da main + 138
    23  libdyld.dylib                       0x05819a25 start + 1
    24  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by sjchmiela** [comment]
@stereodenis could you please pull from this branch and try again? If the latest commit doesn't help, I don't know what can…

**Comment by stereodenis** [comment]
@sjchmiela still not working for me. will wait for others

**Comment by crysfel** [comment]
Unfortunately is not working for me either.  I'm getting this error:

```
2016-05-21 21:52:02.880 [error][tid:main][RCTUIManager.m:1100] Error setting property 'src' of RCTVideo with tag #243: Exception thrown while executing UI block: Cannot remove an observer <RCTVideo 0x12ee61880> for the key path "rate" from <AVPlayer 0x17001ee30> because it is not registered as an observer.
2016-05-21 21:52:02.967 Hymnal[16849:6643744] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x17420b110 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x170251f10> (
<NSKeyValueObservance 0x1700ca2c0: Observer: 0x12ee61880, Key path: rate, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170246fc0>
)'
*** First throw call stack:
(0x1830682d8 0x194cdc0e4 0x183068218 0x183eed810 0x1953b1910 0x100514f94 0x100519c28 0x18301f7f8 0x18301d8a0 0x182f492d4 0x18c9a76fc 0x187b46f40 0x10009863c 0x195386a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by getnashty** [comment]
Just pulled also getting:

```
2016-05-23 22:48:02.225 [error][tid:main][RCTUIManager.m:1042] Error setting property 'src' of RCTVideo with tag #1034: Exception thrown while executing UI block: Cannot remove an observer <RCTVideo 0x1482d55f0> for the key path "rate" from <AVPlayer 0x1481643f0> because it is not registered as an observer.
2016-05-23 22:48:02.312 burnmob[3911:1545350] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x14842d350 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1486388f0> (
<NSKeyValueObservance 0x1482f2470: Observer: 0x1482d55f0, Key path: rate, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x148431110>
)'
*** First throw call stack:
(0x183672db0 0x182cd7f80 0x183672cf8 0x183fc6d80 0x189d04898 0x183fc6cb0 0x189d05d48 0x1831198e8 0x100335a3c 0x10033b4e4 0x183628d50 0x183626bb8 0x183550c50 0x184e38088 0x18883a088 0x1000338fc 0x1830ee8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Pull request merged**
