### PR TITLE
Audio mix with other apps for iOS

### PR DESCRIPTION
**Pull request by euharrison**
This PR adds a feature to control how audio from video can mix with audios from others apps in iOS.

It's uses the options [AVAudioSessionCategoryOptionMixWithOthers](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionmixwithothers) and [AVAudioSessionCategoryOptionDuckOthers](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptionduckothers)

It's helps https://github.com/react-native-community/react-native-video/issues/1103 and https://github.com/react-native-community/react-native-video/pull/959. It's also highly referenced by https://github.com/react-native-community/react-native-video/pull/403.

I'm not a iOS developer so please fells free to points to me any Obj-C error.

Sample:

```js
<Video
  ...
  mixWithOthers="mix" // or "duck"
/>
```

### CODE REVIEW

**Comment by jensellfors** [comment]
This looks good to me @euharrison, I can see how this could be useful. Thanks for submitting it! Is there a similar property for Android we can implement?

**Comment by jensellfors** [comment]
I guess `ignoreSilentSwitch` is iOS only so then by that logic this can be added too :) Just make sure docs are clearly staging it's for iOS only.

**Comment by euharrison** [comment]
Thanks that you appreciate @jenshandersson :)

I added the `Platforms: iOS` in the README. If you suggest to add it in another file, please let me know
https://github.com/react-native-community/react-native-video/pull/1978/files#diff-04c6e90faac2675aa89e2176d2eec7d8R541

**Comment by jensellfors** [comment]
Ah right, great. Can you add a line in the changelog as well @euharrison? Check other PRs to see how, basically a explanation and reference to PR

**Comment by euharrison** [comment]
Done ✅

**Review by lousyfisherman07 — APPROVED** [review]

**Review by lousyfisherman07 — COMMENTED** [review]
Jsusj

**Pull request merged**
