### PR TITLE
iOS: Adding workaround to fix Dolby Atmos playback on iOS 15

### PR DESCRIPTION
**Pull request by aolivier**
Currently, we discovered that Dolby Atmos does not correctly playback on iPhones running iOS 15.x (see #2554). This PR includes a workaround to fix Atmos playback without negatively impacting other platforms, until it is fixed by Apple.

To test playback, use the[ Dolby Atmos test stream](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.5/Test_Signals/muxed_streams/HLS/Manifest_fMP4/Audio_ID_720p_50fps_h264_special_6ch_640kbps_ddp_joc.m3u8). If the file is playing back in Atmos, the user will hear an alternating static noise. If the file is not playing back in Atmos, the user will hear static in mono. See Dolby Atmos device support [here](https://developer.dolby.com/platforms/apple/ios/device-support/#:~:text=%20%20%20%20Device%20%20%20,with%20S%20...%20%2024%20more%20rows%20).

Hopefully Apple will fix this in a future release, but until then...

## Description of workaround

- Apple handles events coming from AirPods as Remote Command events
- By adding a handler for spatial audio remote command events, we indicate to the OS that the device is capable of playing spatial audio (otherwise, it is never able to figure this out)
- Whenever we play video, we must add this event handler that returns a success status for all remote command events
- Whenever we stop video or destroy the player, remove this event handler

## Discoveries during testing:

- Dolby Atmos does not work in the native player on supported iPhone devices starting at iOS version 15.0. In previous iOS versions (14.x), Atmos playback worked with both supported headphones (AirPods  3) and built-in speakers where applicable.
- If displaying video using an AVPlayerViewController, it is possible to get Atmos to play by skipping around the video after it has been playing for several seconds. Atmos will never render on first time playback, or without manually seeking.
- It is never possible to get Atmos playback when using an AVPlayer / AVPlayerLayer

### CODE REVIEW

**Comment by Fedeorlandau** [comment]
This is great!

**Comment by nickfujita** [comment]
@aolivier would you mind testing this PR for the iOS conversion to swift? It does not have the changes you have made here, but I'd be happy to add them in afterwards. I'm looking to have anyone who has contributed to ios test out the converted version. Please be aware that there is a required update to add `use_frameworks! :linkage => :static` to your project Podfile
https://github.com/react-native-video/react-native-video/pull/2527

**Comment by hueniverse** [comment]
@aolivier Are you still interested in getting this merged? It would require a rebase to start a review process. Thanks!

**Comment by hueniverse** [comment]
Closing due to lack of response (from the original submitted or anyone else to review and rebase). If someone wants to pick this up please open a new PR that ports this code into the current master. We are doing our best to start clean with v6 which requires being a bit aggressive in closing stale PRs that are over a year old. Please don't consider this dismissing of your work and contribution - it's greatly appreciated.

**Pull request closed without merging**
