### PR TITLE
Fix src type=nil NSDictionary crash

### PR DESCRIPTION
**Pull request by abrahambotros**
- Use NSNull object in NSDictionary when type (or URI) missing from supplied
  src object.
- In addition, defensively supply valid strings for URI and type from JS.

Looks like this should help with https://github.com/react-native-community/react-native-video/issues/449 and possibly https://github.com/react-native-community/react-native-video/issues/443. I'm seeing the crash behavior in a full external app, not just the example app. Credit to @smkhalsa (https://github.com/react-native-community/react-native-video/pull/454) and @LiuCao (https://github.com/react-native-community/react-native-video/issues/449#issuecomment-272760480) for separately suggesting these fixes; I'm just putting the suggestions together here with some minor tweaks.

### CODE REVIEW

**Comment by abrahambotros** [comment]
Updated to include relevant changes from https://github.com/react-native-community/react-native-video/pull/444 in commit https://github.com/react-native-community/react-native-video/pull/455/commits/65d93a4bee5aaeaf015ce17ffe3f46730879d3e8.

**Comment by krailler** [comment]
I have same problem.. :/

**Comment by oblador** [comment]
I'm experiencing the same thing and this PR fixes it. Despite being a RNC member I cannot review nor merge this so I'm hoping @mattapperson will :-)

**Comment by ivpusic** [comment]
the same here

**Comment by zyonnetworks** [comment]
Same

**Pull request merged**
