### PR TITLE
Added support for playing multiple videos. iOS only.

### PR DESCRIPTION
**Pull request by thsig**
Enables playing multiple (remote or local) videos as a single seamless
video. Each segment is buffered in turn. Currently iOS only.

**The JS API is changed accordingly to also accept arrays of source objects
for the source prop, while still accepting objects for the single-clip case.**

Example:

``` javascript
// Play the supplied videos in order, as a single video
<Video source={[
         {uri: "https://foo.com/clip1.mp4"},
         {uri: "https://foo.com/clip2.mp4"},
         {uri: "https://foo.com/clip3.mp4"}
       ]}
... />

// Passing a single object works as previously
<Video source={{uri: "https://foo.com/clip1.mp4"}}
... />
```

I mentioned this feature here https://github.com/brentvatne/react-native-video/issues/127.

I'm very open to suggestions or criticisms on this API change, or the changes to the Objective C code :)

The gist of the changes to the Objective C code is the following:
1. The `playerItem` for `_player` is now loaded with an `AVMutableComposition` instead of a straight-up `AVAsset`/`AVURLAsset`.
2. I couldn't get `AVMutableComposition` to load remote assets quickly enough (it was painfully slow for some reason, was unable to find any resources on the topic), so I added `_bufferingPlayer`, which is loaded with the corresponding asset for each clip (this time as an `AVURLAsset`, not an `AVMutableComposition`, to make it buffer properly like the current single-clip player does).
3. The buffering logic then sequentially proceeds through each clip in order as they finish loading (so it doesn't start loading clip `N+1` until clips `0..N` have been loaded).

As far as I can tell, this plays nice with everything else (scrubbing works as though the composite clip is one seamless clip, I didn't have to touch the repeat implementation etc.) since, as far as `_player` and `_playerItem` and their associated logic are concerned, all I did was initialise `_playerItem` differently and add some custom buffering (which shouldn't interfere with anything else).

I look forward to your feedback!

Cheers,
Thor

### CODE REVIEW

**Comment by thsig** [comment]
Since I originally made this pull request, I've added support for seeking by clip (using `seekToClip` on the `ref`, similarly to `seek`), and a two new callbacks: `onSeekToClip` and `onClipEnd` (the second is called when a clip finishes playing, but not when all clips are finished, since that's already handled by `onEnd`).

Any feedback on these changes in general?

Thanks!
Thor

**Comment by brentvatne** [comment]
Hey @thsig - sorry I didn't get back to you here, I haven't had time to work on this and was very swamped at the time with React Conf things. I will try to review it in the next couple of weeks.

**Comment by tomprogers** [comment]
After switching to this fork, all my videos are playing back in landscape orientation (despite being recorded in portrait). There's also a weird (but very funny) zoom effect that is applied to each clip every time it plays.

EDIT: I've confirmed this.

When using this branch, every video captured using `react-native-camera` will play back at a 90-degree angle relative to the angle at which it was recorded. I.e.: if you record in landscape, it will play in portrait. If you record in portrait, it will play in landscape. My `react-native-camera` component _does_ specify `orientation="portrait"`, and I've configured my iPhone with Portrait Orientation Lock: On.

I can't follow obj-c, so I have no idea what the cause is. I have looked at the JS bridge, and there don't appear to be any options for controlling this behavior.

**Comment by thsig** [comment]
No worries @brentvatne, good to see there are some eyeballs on this branch now!

@tomprogers: I haven't encountered these behaviours myself, not sure what would be causing them.

I'm very open to criticism of this branch and don't have strong opinions on the particulars of my changed implementation — we needed this functionality for our app so we went ahead and got it done. Since we're using this functionality already, I'm happy to spend some time on making any changes needed for a merge.

**Comment by tomprogers** [comment]
I appreciate your work, @thsig 8)

I'm investigating this because I'm hopeful it will eliminate the bright white flash I'm getting between clips in my own home-rolled playlist support (done in JS, not obj-c). FWIW, you appear to have programmed to the same API that I did; I find that convergence reassuring.

**Comment by thsig** [comment]
Hi guys, has anyone had time to review (or just skim) the general implementation here?

Of course, we'd still have to bring in the changes that have been made on `master` since the branches diverged, but there's other functionality we've been wanting to add to the library which we'd have to make on top of the multiple video functionality (since we're already using and depending on it). So we're hoping we don't have to start thinking of this as our own separate fork of the library with other enhancements added on top. We're also keen on getting input from everyone else.

We're up for doing whatever work's required for it to be accepted to `master` — I realize everyone's very busy, but it would be great to get some preliminary reactions to start with. That way we could get started on any changes that need to be made, in preparation for when the maintainers have time to look at it in detail in preparation for a merge.

Thanks!
Thor

**Comment by thsig** [comment]
(Sorry about that, clicked "Close and comment" by accident!)

**Comment by thsig** [comment]
Hey guys, just checking in on this again. Is there anything particular about the implementation here that's keeping us from moving toward a merge?

I'm more than willing to put in work to help address any architectural (or other) concerns there may be about this branch. Would be great to be able to contribute to the main repo in the future instead of continuing to maintain our own fork.

Thanks again!

**Comment by getnashty** [comment]
+1 I'd like to see this merged too..

**Comment by remymiralles** [comment]
+1 to merge this one

**Comment by brentvatne** [comment]
Hi @thsig - would you like to take this repo over? I no longer have time to work on it :( Sorry

**Comment by thsig** [comment]
Thanks for the add, @brentvatne! :)

I'm canceling this pull request now, as in the meantime I've written a major re-implementation (currently iOS only) that supports caching, multiple videos and prioritises network traffic to the most recently mounted video player instances among other things (useful e.g. on a feed with several players). It's also not hacky like this previous branch, as it uses `NSURLSession`-s, `AVAssetResourceLoaderDelegate` etc. to do things properly.

I don't have permission from my team to open-source it right away, but I hope to be able to do so in the coming months.

Eventually, I hope to propose merging it into this, the main repo, and concurrently to adapt that implementation to include other contributions that have been made here in the meantime. Until then, we'll be using it in production and testing it thoroughly, so I hope it will come to be a solid contribution to the ecosystem.

Thanks, guys!

**Comment by TylerNoblett** [comment]
@thsig I agree with @JLLLinn  - did you get a working solution? If so, this would really help me in a project I'm working on

**Pull request closed without merging**
