### PR TITLE
fix(android): check disableFocus when state is ready

### PR DESCRIPTION
**Pull request by YangJonghun**
#### Update the changelog
fix(android): check disableFocus when state is ready

#### Describe the changes
check `disableFocus` prop when state is ready (currently only works on playback toggle)

### CODE REVIEW

**Comment by freeboub** [comment]
I don't understand why you do this change ...
Audio focus and keep screen on are 2 differents features, controlled independently.
No need of this change in my point of view

**Comment by YangJonghun** [comment]
@freeboub 
You're right, I was just trying to sync the behavior with [this code](https://github.com/react-native-video/react-native-video/blob/master/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L1015-L1017).
I think it would be better to remove the `if (!disableFocus)` from the existing code, what do you think?

**Comment by freeboub** [comment]
@YangJonghun I agree, removing the other reference makes more sense !

**Comment by YangJonghun** [comment]
@freeboub I fixed it. thanks!

**Review by KrzysztofMoch — APPROVED** [review]

**Pull request merged**
