### PR TITLE
Fix for #1150 and improvements for #1143

### LINKED ISSUE #1150: iOS Video not displaying in release mode from bundled assets
### Current behavior
Video does not display in 'Release' Build Configuration' in iOS

### Reproduction steps

```
<Video style={styles.landingVideo} muted repeat resizeMode="cover" source={require('../../assets/videos/bg.mp4')} />
```

Build in iOS a choose 'Release' build configuration by changing the scheme cmd + shift + <

### Expected behavior
Video to display

### Platform
Which player are you experiencing the problem on:
* iOS

Package version 3.1.0
react-native 0.56.0

### PR DESCRIPTION
**Pull request by ashnfb**
@cobarx @ahmetabdi
Fixes #1150 
Improves #1143 (onLoad -> textTracks returns only valid sideloaded vtt)

### CODE REVIEW

**Comment by cobarx** [comment]
@ashnfb Thanks for all your contributions!

Did you by any chance figure out how to disable sideloaded tracks? I'm still waiting to hear back from my contact.

**Comment by ashnfb** [comment]
@cobarx I gave disabling tracks a try.  I'm a little frustrated with the lack of AVPlayer docs.  I'll try and spend a bit more time on it.

**Comment by cobarx** [comment]
@ashnfb Yup, AVPlayer is great when it works, when it doesn't you're just out of luck.

I was thinking about this last night and I don't think we want the fallback code if it can't find the requested track. The way that code works right now is it will only use the fallback if the system Captions preference is enabled, so the behavior will be inconsistent. I think it's totally reasonable to say that if you request an invalid track nothing happens. Really it should throw an error, but there's no framework for it (onError has already been documented as only being for load errors). Also, we don't use the fallback code on Android, so the behaviors are different. Do you have an objection to me reverting that part of the code?

**Comment by ashnfb** [comment]
@cobarx no objection to reverting that code!

**Pull request merged**
