### PR TITLE
Feature/saaa 9116 atv audio focus

### PR DESCRIPTION
**Pull request by joudard-wyplay**
Thanks for opening a PR!
Since this is a volunteer project and is very active, anything you can do to reduce the amount of time needed to review and merge your PR is appreciated.
The following steps will help get your PR merged quickly:

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Focus the PR on only one area
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until it gets fixed.
If you're touching multiple different areas that aren't related, break the changes up into multiple PRs.

#### Describe the changes
Add a note describing what your PR does. If there is a change to the behavior of the code, explain why it needs to be updated.

### CODE REVIEW

**Comment by evoactivity** [comment]
Hi @joudard-wyplay 👋

Thanks for submitting your first PR.

This will need some work before it can be landed including a rebase. Most work right now is happening on master for version 6, this looks like it was forked from an older copy of version 5.

**Can you please explain what this fixes or adds** and we can decide if it should be merged to v6 or v5 or both.

There seems to be unrelated work in the PR too, some dependencies and an analytics prop that would need to be removed.

**Comment by joudard-wyplay** [comment]
Ho sorry, I think I just messed up the repo  / master branch
I was just making an update on the old fork we work with
only the two last commit could be of general interest

**Comment by freeboub** [comment]
I think youbora support can make sens ! :) Even if It would need some rework

**Comment by evoactivity** [comment]
@freeboub maybe a COOKBOOK.md could be added with a tutorial on how to integrate with an analytics platform? I feel like analytics should be left to the consumer. If we add youbora why not any of the other platforms? Will be more to maintain.

**Comment by freeboub** [comment]
@evoactivity I agree about maintenance, I already integrate something like 5 differents analytics library and each one have completly different API ... so the cookbook will be a nightmare to maintain :) let's wait and see

**Pull request closed without merging**
