### PR TITLE
[Android] Font Size and padding Botton Subtitles

### PR DESCRIPTION
**Pull request by allinelara**
Fix issue [#1335](https://github.com/react-native-community/react-native-video/issues/1335)

**Font size**

Before the font size of the subtitles was set by default for Android and the default size was really large and looks weird in some devices. It was no possible to set the font size via JavaScript or editing the VTT file. Now with this changes it is possible to set a font size via JavaScrip using the props: fontSizeTrack.  

**Padding botton** 

It seems that in some devices the subtitles were hidden, so with the props paddingBottonTrack is possible to set via JavaScript a padding botton to position better the subtitles in the screen.

### CODE REVIEW

**Review by CHaNGeTe — APPROVED** [review]

**Comment by reime005** [comment]
can this be merged?

**Review by CHaNGeTe — CHANGES_REQUESTED** [review]
I would suggest changing the prop name `paddingBottonTrack` (be careful, bottom is wrong spelled)
Also I would make splicit on the Readme that the values are 0-1 corresponding to screen percentage: 0 (0%), 1 (100%)

Also it will be great to have the corresponding implementation on iOS, let me know if you can also implement it there.

**Comment by CHaNGeTe** [comment]
@allinelara I have made a PR to your branch trying to mimic the integration on iOS.
https://github.com/allinelara/react-native-video/pull/1

**Comment by CHaNGeTe** [comment]
Also README is updated, please let me know if you find any wrong info

**Review by domborr — CHANGES_REQUESTED** [review]
Hi, please change these values:
1.- on README.md "paddingBottonTrack" into "paddingBottomTrack" (line 249 and lines 817, 818, 819 and 820)
2.- on Video.js "paddingBottonTrack" into "paddingBottomTrack" (line 438)
3.- on ExoPlayerView.java:
 a) "setPaddingBottonTrack(float paddingBottonTrack)" into "setPaddingBottomTrack(float paddingBottomTrack)" (line 92)
b)  "subtitleLayout.setBottomPaddingFraction(paddingBottonTrack)" into "subtitleLayout.setBottomPaddingFraction(paddingBottomTrack)" (line 93)
4.- on ReactExoplayerView.java:
a) "setPaddingBottonTrack(float paddingBottonTrack)" into "setPaddingBottomTrack(float paddingBottomTrack)" (lines 1170)
b) "exoPlayerView.setPaddingBottonTrack(paddingBottonTrack)" into "exoPlayerView.setPaddingBottomTrack(paddingBottomTrack)" (line 1171)
5.- on ReactExoplayerViewManager.java:
a) "private static final String PROP_FRONT_SIZE_TRACK" into "private static final String PROP_FONT_SIZE_TRACK" (line 62)
b) "private static final String PROP_PADDIND_BOTTON_TRACK = "paddingBottonTrack" " into "private static final String PROP_PADDING_BOTTOM_TRACK = "paddingBottomTrack" " (line 63)
c) "@ReactProp(name = PROP_FRONT_SIZE_TRACK)" into "@ReactProp(name = PROP_FONT_SIZE_TRACK)" (line 272)
d) "@ReactProp(name = PROP_PADDIND_BOTTON_TRACK" into "@ReactProp(name = PROP_PADDING_BOTTOM_TRACK" (line 277)
e) "public void setPaddingBottonTrack(final ReactExoplayerView videoView, final float paddingBottonTrack) {" into "public void setPaddingBottomTrack(final ReactExoplayerView videoView, final float paddingBottomTrack) {" (lilne 278)
f) "videoView.setPaddingBottonTrack(paddingBottonTrack);" into "videoView.setPaddingBottomTrack(paddingBottomTrack);"

**Comment by allinelara** [comment]
Fix it in the commit 2786473

**Comment by allinelara** [comment]
Fix it!

**Comment by pybuche** [comment]
@CHaNGeTe @domborr gentle ping on this PR: Can we merge it and release a new version?
I don't mind doing it if you give me contributor rights 🙏

**Comment by domborr** [comment]
@pybuche If you can explain me how to give you contributor rights, I will do it!

**Comment by pybuche** [comment]
@domborr Sorry, I thought you were part of the contributors, but you don't have the contributor badge on your profile. If you were, you would have access to the "Settings" menu:
image

Or maybe you'd only have contributor rights and wouldn't be able to add me here. 

I suppose you don't have write access either? Meaning you can't merge this PR if you approve it, right?

**Comment by domborr** [comment]
@pybuche Yes, unfortunately I can't do nothing.

**Comment by cosmin5mins** [comment]
This is still an issue

**Comment by freeboub** [comment]
Hi,
I agree this should be merged.
Just one thing, is it possible to merge the 2 props in one single object (subtitleStyle for exemple) i know some other ticket which request to change background color of subtitles also.
Thank you

**Comment by hueniverse** [comment]
@freeboub are you able to make the necessary changes to get this merged? Otherwise I'm going to close it.

**Comment by freeboub** [comment]
@hueniverse no problem, I will do it in few days !

**Comment by freeboub** [comment]
I will close this PR, to be replaced by: https://github.com/react-native-video/react-native-video/pull/2759
I merge all the props in a single object. and change a little bit api for padding management.

**Pull request closed without merging**
