### PR TITLE
Fixes bug that causes player to crash when fullscreening at initialization (#1234)

### PR DESCRIPTION
**Pull request by fossage**
## Overview

Because the `setSrc` method now runs async, it is possible for the player to not be initialized at the point a user calls the `setFullscreen` method via `presentFullscreenPlayer`. A good example of this is when a user of the library wants to fullscreen a video as soon as the ref for the video component is captured. 

To prevent this problem, in the case where the user is trying to fullscreen the video but the player has not yet been initialized, this will set a flag letting the system know that the user would like to fullscreen the video as soon as the player is initialized. Upon initialization, that flag will be read, the player will be fullscreened, and the flag will be set back.

See (#1234)

### CODE REVIEW

**Comment by dozel** [comment]
Is this going to be merged at any point? Would love this fix

**Review by n1ru4l — APPROVED** [review]

**Comment by n1ru4l** [comment]
@fossage could you please rebase on master?

**Comment by fossage** [comment]
@n1ru4l , branch has been updated.

**Comment by kcalmes** [comment]
When will this pull request be accepted?

**Comment by nmalancea** [comment]
Any plans to get this merged? `fullscreen` property is not working for me.
Getting:
```
Exception thrown while executing UI block: Application tried to present modally a view controller <RCTVideoPlayerViewController> that has a parent view controller <UIViewController>
```

**Pull request closed without merging**
