### PR TITLE
ios Caching Support

### PR DESCRIPTION
**Pull request by n1ru4l**
I want some discussion about this (related to #99). I am currently working on an iOS app so ~~I have no needs for android right now.~~ **Edit:** Android integration will follow soon!

Would love some feedback from guys that are more into objective c. This is almost the first objective c I have ever written 😅.

I added the libraries that I am using [SPTPersistentCache](https://github.com/spotify/SPTPersistentCache) and [DVAssetLoaderDelegate](https://github.com/vdugnist/DVAssetLoaderDelegate) as ~~git submodules as I have seen it [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image)~~ cocoapod dependencies.
I am using a the setup described here: http://facebook.github.io/react-native/docs/integration-with-existing-apps.html.

if you would setup react-native with this library your Podfile should look similar to this:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'VideoCaching' do
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification',
    'RCTCameraRoll',
    'RCTSettings',
    'RCTBlob',
    'RCTGeolocation',
    'DevSupport'
  ]

  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
end
```

## **Functionality**

Aggressive Caching based on the uri (similar to [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image)). 
The storage is backed by [SPTPersistentCache](https://github.com/spotify/SPTPersistentCache). (LRU Cache). Might be possible to make this someway more customisable.

Since it is not possible to create an [`AVAsset`](https://developer.apple.com/documentation/avfoundation/avasset) from NSData which SPTPersistentCache returns. I also added another layer which saves the file to the devices temporary folder (Google says it is cleared after 3 days). So after three days it will have to be refetched from the persistent storage ([SPTPersistentCache](https://github.com/spotify/SPTPersistentCache)). This results in additional storage size.

### **Method 1:**

Check out the example app located in [`examples/video-caching`](https://github.com/n1ru4l/react-native-video/tree/implement-ios-caching/examples/video-caching)

**UPDATE**: There is now a README.md file which describes how you can test the implementation

Commands for initializing the project:

```
yarn
cd ios
pod install
cd ..
```

After you initialized the project, you can open the `ios/VideoCaching.xcworkspace` project in xcode (and run it your device/simulator).

### **Method 2:**

Use my private fork `@n1ru4l/react-native-video@3.1.0-alpha.4` in your project. (The project will also require a proper cocoapods setup). You can copy it from the example app ([`examples/video-caching`](https://github.com/n1ru4l/react-native-video/tree/implement-ios-caching/examples/video-caching)) and replace the pod with the following line:

`pod 'react-native-video/VideoCaching', :path => '../node_modules/@n1ru4l/react-native-video/react-native-video.podspec'`

## **TODO**
- [x] Clean up debug logging
- [x] Make feature optional (react-native-camera did this with additional frameworks https://github.com/react-native-community/react-native-camera/pull/1341/files)

### CODE REVIEW

**Comment by roycclu** [comment]
Thanks man.
This is a very welcome feature. 
Especially given the large costs of loading video from network everytime. 
Has any core contributors looked at this?

**Comment by n1ru4l** [comment]
**roycclu wrote:**
> @n1ru4l I see you added SPTPersistentCache in your podspec as dependency. Any idea why the header isn't found?

Have you followed all steps for configuring react-native with CocoaPods and opened the `.xcworkspace` project?

I updated the `Podfile` above to match the latest react-native version `0.56.0`.

FYI: I am using my fork that is published to npm `@n1ru4l/react-native-video`), without any issues.

**roycclu wrote**
> Has any core contributors looked at this?

Nobody did comment this Pull Request yet, so I doubt that anybody checked it out.

I will rebase on master soon (and the android implementation should also follow soon).

**Comment by n1ru4l** [comment]
**@BunHouth wrote** (https://github.com/react-native-community/react-native-video/issues/99#issuecomment-402678108):
>  I got error as image bellow.  
image

There was indeed an issue. I merged in master and fixed these issues, I also updated the example app (`examples/video-caching`).

My new private fork version is also published as `@n1ru4l/react-native-video@3.1.0-alpha.2`

I would love if you could give me some feedback whether it now works for you or not.

**Comment by n1ru4l** [comment]
**@corbax wrote**
> @n1ru4l Do you think it would be valuable to make the cache size a configurable prop?

I do think that configuring the cache size and setting the expire dates should be done via a static method on the `Video` component upon application boot time.

Something like:

```js
import Video from 'react-native-video'

Video.initializeCache({
  defaultExpirationPeriod: 1000 * 60 * 60 * 24 * 30, // 30 days
  garbageCollectionInterval: 1000 * 60, // every minute
  sizeConstraintBytes: 1024 * 1024 * 100, // 100mb
})

```

What do you think?

In the future we could also make it possible to initialize multiple caches for different purposes. For now I would like to keep it simple.

**@corbax wrote:**
> With the Cocoapods, I don't want to get into a situation where everyone who installs react-native-video needs to setup Cocoapods, installing needs to be as simple as possible. I'm happy to help out with making it an optional dependency in whatever way I can, let me know if you need assistance.

For me CocoaPods works best, I had several issues with different projects by using `react-native link`.

We can utilize the same procedure as here: https://github.com/react-native-community/react-native-camera/pull/1341/files

However I am currently clueless on how to include the dependencies when someone does not use CocoaPods. I would love to get some input from you for this topic.

**Comment by cobarx** [comment]
@n1ru4l wrote:
> I do think that configuring the cache size and setting the expire dates should be done via a static method on the Video component upon application boot time. 

Since the cache is shared between all the video components, that totally makes sense. I could even see creating a VideoCache component since there's going to be a lot of functionality, e.g. 
`import Video, { VideoCache } from 'react-native-video';`

> However I am currently clueless on how to include the dependencies when someone does not use CocoaPods. I would love to get some input from you for this topic.

Since Apple doesn't have an official solution, Cocoapods is pretty much the best option. The only alternatives I know of are downloading tarballs or using Carthage. For internal company projects, you can include the GitHub repo as submodule if that's what you want.

I don't have any disagreement with requiring CocoaPods for enabling caching. I just want to make sure the default use case with `react-native link` is as simple as possible so people can get up and running. Advanced users can go through the extra steps to get functionality they need. We can use conditional imports like RNCamera is doing to enable optional enhancements and everyone will be happy.

**Comment by n1ru4l** [comment]
@cobarx I made the video caching optional in 4f386d2

I also updated the example app and added instructions on how to test whether caching is working or not.

I still need to test whether normal react-native link works (since i updated some paths).

I will also try to tackle cache configuration in the next days.

The newest test release is `@n1ru4l/react-native-video@3.1.0-alpha.3`.

**Comment by cobarx** [comment]
@n1ru4l Awesome, you are a beast getting it done that fast!

I looked it over and all the includes look good after a quick glance. This is already a massive PR, I would suggest we get this merged without the ability to configure the cache settings, then handle that separately.

One thing I noticed is that the cache prop is not currently implemented. We should remove that until it's ready. I do think it would be a good option to have even with the conditional imports since you may want to only cache some videos.

Also, we need docs on how to set this up and how it works. I would be good with having a separate doc just for caching if there's a lot of info. Install instructions can go in the main README.

**Comment by n1ru4l** [comment]
@cobarx I updated the PR to add some instructions and also removed the `cache` prop.

The newest test release is `@n1ru4l/react-native-video@3.1.0-alpha.4`.

**Comment by geniuscd** [comment]
This is a major feature! thanks @n1ru4l for your efforts! I'm ready and happy to test it and contribute. I was implementing such feature using blob fetch technic, but I don't think its going to work while streaming video.
Just a thought, why this feature isn't enabled by default unless the user specify otherwise?

**Comment by roycclu** [comment]
Your speed is impressive. I'd be down to try your fork and verify or leave some comments. Currently SPTPersistentCache is not installing, maybe some network setting problem. Report back soon.

**Comment by BunHouth** [comment]
@n1ru4l it work fine on your latest code. thanks.

**Comment by roycclu** [comment]
@n1ru4l caching works. cocoapod set up was pretty easy too.

**Comment by n1ru4l** [comment]
For those interested: I started experimenting with caching for android. Check out `@n1ru4l/react-native-video@3.1.0-alpha.5` (caching for android is enabled by default in that build).

The underlying implementation changes are present in this commit: https://github.com/n1ru4l/react-native-video/commit/8248f2c8c1a670bce5480d6a053acf1f2e3eae3a

The underlying cache is https://github.com/danikula/AndroidVideoCache

I am aware that ExoPlayer has also able to provide caching, however I could not get it working. We have an android guy that is working on this.

**Comment by RalfNieuwenhuizen** [comment]
@n1ru4l lately I've been working on the ExoPlayer cache implementation you mentioned, and found out it works quite well actually. See https://github.com/react-native-community/react-native-video/pull/1148 for more information.

**Comment by cobarx** [comment]
Going to merge this this week, thanks everyone for testing this. And thanks @n1ru4l for getting this implemented and ready!

Can you update the PR to handle the merge conflicts. I don't see the Android caching code in this PR, I'd suggest we merge those as a separate PR once it's ready, I don't want having to review that to hold this up.

**Comment by cobarx** [comment]
I set it up via Podfile like you put in the description, and I'm getting an error:
Video has no PropType for native prop RCTVideo.cache of native type BOOL

Also, if I create a new project and use `react-native link`, the paths are coming in with a Vendor directory (see screenshot). So when it goes to compile it can't find the iOS code. Can you take a look into that.
vendor

**Comment by n1ru4l** [comment]
@cobarx You have to remove the `cache` property from the `<Video/>` component.

I also removed the Vendor code and adjusted the file paths in b83f3a57db0ec3a0dde69b92850c61d1e1790335.

**Comment by cobarx** [comment]
@n1ru4l I'm pretty sure the `cache` error is coming from being defined in RCTVideoManager.m.

I'm trying to test this on the Simulator and not having much luck, do you know if it will work there? If not, we should document that. I keep getting -11800 or -11828 errors if I turn WiFi off on my laptop, even with extremely short videos.

**Comment by n1ru4l** [comment]
@cobarx I forgot to remove the cache property, however for me it was not causing any errors 😕

Both examples  `basic` and `video-caching` are fully functional for me. 

Also the caching works fine on the simulator as well as on real devices. Can you please provide a repository that shows these errors? I would like to investigate more on that!

**Comment by cobarx** [comment]
Ok, I went back and tested with the video you're using in the example and it works great online and offline. It appears that certain videos can cause problems.

**URLs with query strings at the end, e.g. ?size=large**
The video will load fine while online, but if I switch to offline it throws a -11828 error. Once I go online, it still throws the error. If I get rid of the query string, everything works.

Example: 
http://techslides.com/demos/sample-videos/small.mp4?variable=value

**HLS Playlists**
Won't load at all, throws a -11800 error. I made sure to turn off all the audio & text track selection code.

Examples:
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

**Comment by n1ru4l** [comment]
@cobarx wrote:

>**URLs with query strings at the end, e.g. ?size=large**
The video will load fine while online, but if I switch to offline it throws a -11828 error. Once I go online, it still throws the error. If I get rid of the query string, everything works.

We should also handle URLs without file extension. Best way would be to parse the Content-Type header and save the file with the corresponding file extension.
Any further concerns before I start working on this?

Edit: This requires work on a dependency (I already created a pull request https://github.com/vdugnist/DVAssetLoaderDelegate/pull/5)


@cobarx wrote:

>**HLS Playlists**
Won't load at all, throws a -11800 error. I made sure to turn off all the audio & text track selection code.

Are we fine with just skipping those files from being cached?

**Comment by cobarx** [comment]
@n1ru4l wrote:
> We should also handle URLs without file extension. Best way would be to parse the Content-Type header and save the file with the corresponding file extension.
Any further concerns before I start working on this?

Sounds like a good approach. I'd say go for it, were you thinking there was anything else? My only other wishlist item would be to get the `caching` prop implemented to give some flexibility on what gets cached, however that could go in a future PR.

@n1ru4l wrote:
> Are we fine with just skipping those files from being cached?

This is a huge PR, so I'd love to get it merged asap and avoid further merge conflicts, maintenance, etc. I think that's fine for a first pass. 

HLS support would be great to have. HLS is the most common way to do professional video delivery on iOS, where you need adaptive bitrates, text tracks, and so on. Adding support for it would be pretty significant for the big high-end apps.

**Comment by roycclu** [comment]
Could we include a "Preload" function?
Similar to the react-native-fast-image preload. 

@cobarx thanks for merging this!

**Comment by cihadturhan** [comment]
I'm way more interested in this PR. I have a real-time trivia app which streams audio files and will have up to hundred of thousands of users. So this feature is quite essential to me otherwise I can't have a server to stream so many people at the same time.

**Comment by n1ru4l** [comment]
This pull request is currently blocked by https://github.com/vdugnist/DVAssetLoaderDelegate/pull/5

An alternative way would be to skip all urls that include no file extension from being cached until we got access to the `content-type` header.

**Comment by cobarx** [comment]
I'd say skip them and come back to it later. We want to get this into dev
hands and can continue to add improvements over time. As long it's
documented what's supported and what's not, we're good.

**Comment by n1ru4l** [comment]
@cobarx I fixed all complaints, except the `textTracks` issue. Could need some help with that.

**Comment by cobarx** [comment]
I'd like to merge this into a develop branch and fix the textTracks issues there so we can work on it together. Can you resolve the merge conflicts.

For the file extension / query string stuff, what I mean is the caching.md doc should cover everything a developer needs to know about using caching in their app. If someone has a question, they can refer back to that doc and see what's supported and what's not. It's pretty easy to miss the debug messages if you don't know to look for them.

**Comment by n1ru4l** [comment]
@cobarx done 😊

**Comment by cobarx** [comment]
Ok, all set! I'll start working on the text track stuff shortly.

**Comment by AlexandruVoica** [comment]
Can we get a status update on the caching feature, please? 😅 I am especially interested in the Android implementation.

**Comment by n1ru4l** [comment]
@AlexandruVoica Sure, feel free to implement it and send a pull request!

**Pull request merged**
