### PR TITLE
Added support for automaticallyWaitsToMinimizeStalling property on iOS 

### PR DESCRIPTION
**Pull request by blitzcrank**
#### Describe the changes
This pull request adds the `automaticallyWaitsToMinimizeStalling` property which is available on iOS only starting from iOS 10. The property is set to `true` by default.

From the official Apple documentation (https://developer.apple.com/documentation/avfoundation/avplayer/1643482-automaticallywaitstominimizestal?language=objc)
A Boolean value that indicates whether the player should automatically delay playback in order to minimize stalling.

#### Update the documentation
The property has been added to the documentation

#### Update the changelog
The changelog is updated mentioning the current pull request

#### Provide an example of how to test the change
The changes can be tested with any video by implementing the `automaticallyWaitsToMinimizeStalling` prop on `Video` and setting it to `false`.

### CODE REVIEW

**Review by ashnfb — CHANGES_REQUESTED** [review]
Please correct the formatting (tab) issues in Xcode, and update the docs to specify the default value.
Otherwise looks good!

**Comment by blitzcrank** [comment]
All change requests have been resolved!

**Review by ashnfb — APPROVED** [review]

**Comment by ashnfb** [comment]
@cobarx, @CHaNGeTe I've reviewed this PR, need a 2nd approval and merge

**Review by CHaNGeTe — APPROVED** [review]

**Comment by CHaNGeTe** [comment]
To be released

**Pull request merged**
