### PR TITLE
Fix/issue 2594/content

### LINKED ISSUE #2594: Fairplay skd contentId parse issue with getLicense
# Bug
```
 <Video
        onProgress={onProgress}
        onEnd={onEnd}
        onError={(e) => console.log(e)}
        paused={state?.paused}
        ref={player}
        source={{uri: 'https://n.com/test.m3u8}}
        style={{width: "100%", height: "100%", zIndex: 1}}
        resizeMode={"cover"}
        drm={
              {
                  type: 'fairplay',
                  certificateUrl: `CERT_URL`,
                  base64Certificate: true,
                  getLicense: (spcBase64, contentId, licenseUrl) => {
                    return fetch('LICENSE_URL', {
                      method: 'POST',
                      headers: {
                        ...
                        'Content-Type': 'application/x-www-form-urlencoded',
                      },                     
                    }).then(response => response.text()).then((response) => {
                      console.log(response);
                      return response;
                    }).catch((error) => {
                      console.error('Error', error);
                    });
                  }
            }
        }
      />
```
#### m3u9
```
...
EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://asdsad23ss/rw==", ...
...
```

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 5.2.0

## Steps To Reproduce
- When i set `getLicense` in drm property, below results.

  - Expected results: asdsad23ss/rw==
  - Actual results: asdsad23ss

### PR DESCRIPTION
**Pull request by purpletortoise-choi**

### CODE REVIEW

**Comment by hueniverse** [comment]
@purpletortoise-choi Is there a way of solving this without adding another config option?

**Comment by adityapatadia** [comment]
Why was this closed? Is this resolved?

**Comment by freeboub** [comment]
It was stale, btw it was reimplemented on V6. Should be ok now

**Comment by adityapatadia** [comment]
As in, should we use beta version?

**Comment by freeboub** [comment]
> As in, should we use beta version?

Yes it is available in last 6.0.0 beta ! No maintenance planned on 5.2

**Pull request closed without merging**
