### PR TITLE
New example project and cleanup. Dropping iOS cacheing

### PR DESCRIPTION
**Pull request by jensellfors**
Previously we had 3 example project that were outdated. The purpose of this is to have 1 example project that we can maintain. It's a fresh RN project with 0.62.2. Inspiration and structure has been taken from react-native-datepicker.

Instead of creating separate example RN projects I suggest we just create multiple JS files. Right now I just made a simple basic player that we can easily maintain. 

This removes the example project of cached videos for iOS.
This removed Windows example project, will need help to add it back. (Someone from Microsoft maybe?)

### CODE REVIEW

**Comment by jensellfors** [comment]
@thymikee do you mind having a quick look at this new example/project structure? I saw the discussion you had with @vonovak. I couldn't get ios to work without specifying `react-native run-ios --project-path example/ios`. Everything seems to work fine btw, just not sure it's the ideal setup. Much appreciated 🙌

**Comment by thymikee** [comment]
You can tell CLI where to look for the project through `react-native.config.js`: https://github.com/react-native-community/datetimepicker/blob/master/react-native.config.js

**Comment by jensellfors** [comment]
@thymikee for me it still picks the wrong one, although `react-native config` looks correct

```
module.exports = {
  dependencies: {
    'react-native-video': {
      root: __dirname,
    },
  },
  project: {
    android: {
      sourceDir: './example/android',
    },
    ios: {
      project: './example/ios/example.xcodeproj',
    },
  },
};
```
outputs: (`react-native config`)
```
"ios": {
      "sourceDir": "/Users/jensa/Developer/jensun/play/react-native-video/example/ios",
      "folder": "/Users/jensa/Developer/jensun/play/react-native-video",
      "pbxprojPath": "/Users/jensa/Developer/jensun/play/react-native-video/example/ios/example.xcodeproj/project.pbxproj",
      "podfile": "/Users/jensa/Developer/jensun/play/react-native-video/example/ios/Podfile",
      "podspecPath": "/Users/jensa/Developer/jensun/play/react-native-video/react-native-video.podspec",
      "projectPath": "/Users/jensa/Developer/jensun/play/react-native-video/example/ios/example.xcodeproj",
      "projectName": "example.xcodeproj",
      "libraryFolder": "Libraries",
      "sharedLibraries": [],
      "plist": [],
      "scriptPhases": []
    },
```

But when I run `react-native run-ios`:

```
npx react-native run-ios --verbose
debug Reading /Users/jensa/Developer/jensun/play/react-native-video/example/ios/Podfile
debug Reading /Users/jensa/Developer/jensun/play/react-native-video/example/ios/Podfile.lock
info Found Xcode project "RCTVideo.xcodeproj"
```

Doesn't matter if I use xcodeproj or xcworkspace. Npx or not. 
react-native 62.2
cli 4.8.0

FYI I get the same error when trying to run datetimepicker.

Any ideas...?

**Comment by vonovak** [comment]
@jenshandersson hi, let me know if need some assistance, I should have some time to spare. Thanks.

**Comment by jensellfors** [comment]
Thanks @vonovak but I've verified it's an issue with cli: https://github.com/react-native-community/cli/issues/1103#issuecomment-630187270

**Comment by jensellfors** [comment]
@benoitdion @n1ru4l  @cobarx what are your thoughts on my suggestion? This makes it much simpler to further develop this project and aligns with other RNC projects.

**Review by benoitdion — APPROVED** [review]

**Comment by n1ru4l** [comment]
@jenshandersson It seems like you removed the video caching example. How to test whether the functionality is broken without an example app for it? How to test whether the functionality of the app without caching is broken after applying some changes that are targeted at the caching module without having two apps?

**Comment by jensellfors** [comment]
I didn't know the caching was widely used, was hoping we could deprecate and remove. It's a very niche use case that we don't have an implementation for Android. Again, I think we need to streamline this project otherwise the quality can never go up. 

If we need the caching I suggest enabling it in the example then, if it's supported then we need to support it properly.

**Comment by jensellfors** [comment]
@n1ru4l or maybe we just add it as comments in the example/ios/Podfile, then people can use the optional caching. This way we keep 1 example that we can maintain, I don't feel it's reasonable to have 3 different RN projects with completely different code.

**Comment by jensellfors** [comment]
As discussed with @n1ru4l and maintainers we decided to remove iOS caching as we feel it's not part of the core video player. We can open an issue to discuss other ways of moving caching/offline playback forward, but currently this is out of scope of RNV. (One way would be to add a RNFS wrapper that downloads the assets before starting playback)

If you feel you need this functionality then feel free to stay at 5.0.x.

**Comment by jensellfors** [comment]
This will remove the Windows example code FYI. We would need someone from Microsoft to help out here, adding it back to this new example. Maybe @stmoy @acoates?

**Comment by stmoy** [comment]
Thanks for the FYI @jenshandersson - I'm following up internally to see if we can find someone to add the Windows functionality to the new example.

**Comment by Monte9** [comment]
@jenshandersson any updates on this PR? Looks like a really useful change and would be good to get this merged in.

**Pull request closed without merging**
