### PR TITLE
add stop video function

### PR DESCRIPTION
**Pull request by kbourchbane**
Thanks for lib!
i add a stop video function because for android 6 the app crash when the user navigate or change page without stopping video

### CODE REVIEW

**Comment by danielmarino24i** [comment]
Maybe it is something to have in consideration for `componentWillUnmount`

**Comment by sasaluo** [comment]
how to stop or remove the video? I have the same problem now,when changing pages from A to B and  both pages have video, the app could not  work

**Comment by sasaluo** [comment]
i tried the this.player.stopVideoPlayer() method,however app crashed in android tv

**Comment by jensellfors** [comment]
What is the use case for this? If you want stop the video you can either pause it or remove it from your view, that should stop and deallocate it.

If we introduce a stop function then it needs to be available on all platforms, not just ExoPlayer. It should also probable be a method and not a prop.

**Comment by siokstoksanoks** [comment]
@jenshandersson  when component is unmounting that function stop is needed.
Wouldn't be setting state for unmounting component to change prop for this component.

**Pull request closed without merging**
