### PR TITLE
Changed the implementation to use the view of AVPlayerViewController

### PR DESCRIPTION
**Pull request by pjcabrera**
Changed the implementation to use the view of AVPlayerViewController rather than the AVPlayerLayer of AVPlayer. Also added a showControls property, to show/hide the video player controls.

Made this change because we wanted to show the native controls by default. By setting the showControls property, you can retain the previous behavior.

### CODE REVIEW

**Comment by brentvatne** [comment]
very cool, I'll try this out on the example project and get back to you!

**Comment by brentvatne** [comment]
@pjcabrera - sorry I haven't had a chance to try this yet, will review on Saturday

**Comment by stereodenis** [comment]
@brentvatne did you try?

**Comment by yamill** [comment]
@brentvatne I tested this and it's working for me. Currently using it in one of my projects.

**Comment by PublicParadise** [comment]
@brentvatne @pjcabrera I suspect that this PR is now obsolete after https://github.com/brentvatne/react-native-video/pull/119 got merged.

**Comment by brentvatne** [comment]
indeed, thanks @PublicParadise and @pjcabrera!

**Pull request closed without merging**
