### PR TITLE
Update from View.propTypes to ViewPropTypes to match RN v0.44.0

### PR DESCRIPTION
**Pull request by TBouder**
Update the ViewPropTypes to match the last revision of React Native V0.44.0

> View.propTypes to ViewPropTypes (53905a5) - @bvaughn

https://github.com/facebook/react-native/releases

### CODE REVIEW

**Comment by TBouder** [comment]
The update of the package.json is a buffer. I made a pull request for the react-native-windows package for the same reason.

**Comment by larenelg** [comment]
Would be fantastic if this could please be merged. As View.propTypes is deprecated and will be removed very soon.

**Comment by MarkMurphy** [comment]
This is a really simple pull request people, would love this to get merged.

**Comment by mandriv** [comment]
Any updates on this PR?

**Comment by asgvard** [comment]
This brakes on RN 0.49 and above now, since it's now React 16 beta.5, so this warning is now a fatal error...
Actually it seems to be merged by this PR:
https://github.com/react-native-community/react-native-video/pull/824

**Comment by mandriv** [comment]
@asgvard Yes, the PR you mentioned fixes the problem. Update your `package.json` like this:
 ` "react-native-video": "git://github.com/react-native-community/react-native-video.git#master",`
@mattapperson This PR can be closed.

**Comment by cobarx** [comment]
This has been addressed by #824

**Pull request closed without merging**
