### PR TITLE
Fixed Exoplayer doesn't work with mute=true #1696

### PR DESCRIPTION
**Pull request by andrewchae**
Thanks for opening a PR!
Since this is a volunteer project and is very active, anything you can do to reduce the amount of time needed to review and merge your PR is appreciated.
The following steps will help get your PR merged quickly:

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Focus the PR on only one area
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until it gets fixed.
If you're touching multiple different areas that aren't related, break the changes up into multiple PRs.

#### Describe the changes
Add a note describing what your PR does. If there is a change to the behavior of the code, explain why it needs to be updated.

### CODE REVIEW

**Comment by bwillem** [comment]
Any reason not to merge this? 👍

**Comment by djw27** [comment]
Would be great if this can be merged. Works nicely in our testing.

**Comment by bwillem** [comment]
Works for us too :shipit:

**Review by jensellfors — APPROVED** [review]

**Review by CHaNGeTe — APPROVED** [review]

**Review by jensellfors — APPROVED** [review]

**Comment by jensellfors** [comment]
@andrewchae thanks for submitting this, can you please add a line to the changelog as well. Then we can merge this

**Comment by scgough** [comment]
Is this fix in a release yet? If not do we know when it might be?
Thanks!

**Comment by djw27** [comment]
@scgough looks like it's in 5.1.0@alpha

**Comment by merissaacosta** [comment]
Is there a rough estimate for when this fix will be out of alpha and in a stable version?

**Comment by sharifhh** [comment]
Reproduced with this fix in some cases, will check why and give more details

**Comment by ghost** [comment]
facing same issue in version 5.1.1

**Comment by reyanshmishra** [comment]
same here!!!

**Comment by shravanthium** [comment]
Did Exoplayer update https://github.com/react-native-video/react-native-video/pull/2317 fix this issue?

**Comment by KrushnaNaghate** [comment]
this issue still exists with the current version 5.2.1

**Pull request merged**
