### PR TITLE
support opacity on android

### LINKED ISSUE #1983: [Android] Opacity is black instead of the color of the parent view of a video
# Bug

Android does not behave like iOS for opacity. Android will show a black screen as the opacity increases as to iOS which will reveal the container underneath.

This issue happens when applying opacity to a parent view or directly to the react-native-video component.

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.04 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/<my username>/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. Add RNVideo to any android project
2. Add opacity to the RNVideo component. Notice that iOS can display the background color if RNVideo is transparent.
...

## Expected behaviour

1. Android should not show black background for player if the background parent view is a lighter color

## Reproducible sample code

```
const style = {
    width: 500,
    height: 500,
    opacity: 0.5,
  };
const Component = () =>    ( 
<RNVideo
        source={<ANY VIDEO url or asset>}
        style={style} 
        hideShutterView // hides blackscreen on android
      />)
```

### PR DESCRIPTION
**Pull request by conceptualspace**
- resolves #1983 (thanks @Christian-Athom)
- support video opacity on android; consistent with ios
- to test, set 0.5 opacity on an RNVideo component. with the PR you can see the container underneath; without it the background layer is black

Thanks for opening a PR!
Since this is a volunteer project and is very active, anything you can do to reduce the amount of time needed to review and merge your PR is appreciated.
The following steps will help get your PR merged quickly:

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Focus the PR on only one area
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until it gets fixed.
If you're touching multiple different areas that aren't related, break the changes up into multiple PRs.

#### Describe the changes
Add a note describing what your PR does. If there is a change to the behavior of the code, explain why it needs to be updated.

### CODE REVIEW

**Review by areimann-sf — APPROVED** [review]

**Comment by benoitquero** [comment]
This feature can be very useful !

**Comment by hueniverse** [comment]
@benoitquero If you have the time to test it out and verify it works and approve the PR, it will get it one step closer to being merged!

**Comment by hueniverse** [comment]
Closing due to lack of response (from the original submitted or anyone else to review and rebase). If someone wants to pick this up please open a new PR that ports this code into the current master. We are doing our best to start clean with v6 which requires being a bit aggressive in closing stale PRs that are over a year old. Please don't consider this dismissing of your work and contribution - it's greatly appreciated.

**Comment by hatamsoyunov** [comment]
I added the patch for version 6.0.0-alpha.6, it works, thanks!

```
diff --git a/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java b/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
index 3b7df5b..f33891a 100644
--- a/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
+++ b/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
@@ -125,6 +125,7 @@ public final class ExoPlayerView extends FrameLayout implements AdViewProvider {
             }
         } else {
             view = new TextureView(context);
+            ((TextureView) view).setOpaque(false);
         }
         view.setLayoutParams(layoutParams);
 

```

**Pull request closed without merging**
