### PR TITLE
Fullscreen options for iOS

### LINKED ISSUE #1161: Video on iPad not showing fullscreen
### Current behavior
The app is currently set up to load the video when the component mounts however it is hidden (it's position) until the user clicks an image. Then the video position within the screen and is automatically fullscreen. On iOS iPads (I've tried most version included with Xcode) it does not show however I can hear the audio playing. 

### Reproduction steps
Component mounts, user presses an image, the video appears fullscreen. Works fine on iPhones, Android phones, and Android tablets.

### Expected behavior
Video should become visible in fullscreen mode.

### Platform
iOs iPads

### PR DESCRIPTION
**Pull request by ashnfb**
@cobarx I took a crack at fullscreen options for iOS.

the 'fullscreen' prop is backwards compatible
the new 'fullscreensOption' prop is structured as follows:
{ enabled: true | false,
  preferredOrientation: 'landscape' | 'portrait' | 'default',
  autorotate: true | false }

Preferred Orientation will default to the current device orientation if 'default' is provided, or a non-sensical value is provided.
Autorotate doesn't seem to do anything, but since it is a property of AVPlayerViewController, I've included it.

as a side-effect it also fixes https://github.com/react-native-community/react-native-video/issues/1161

### CODE REVIEW

**Comment by ashnfb** [comment]
Sorry about the spacing issues in the diff for RCTVideo.m.  My team here insists on using 2 physical spaces instead of tabs.

**Comment by cobarx** [comment]
Is there any way you can set it to tabs, commit it, and put it back to spaces? It's a bit tricky to tell what's changed with this many updates.

**Comment by ashnfb** [comment]
Sure no problem, I'll do that.


________________________________

**Comment by ashnfb** [comment]
@cobarx I've reverted back to tab spacing.  The code seems to be a mix though, so it shows more changes than the ones I made, will we need to clean it up / enforce the spacing moving forward.

**Comment by cobarx** [comment]
Is there a way to configure this on a file level similar to how you can include vim directives at the top of the file?

Sorry I haven't taken a look at this, just started a new job and am getting settled in, so my free time has been cut way back. I'll get to this and some of the other PRs fairly soon.

**Comment by ashnfb** [comment]
Hey Hampton,

No worries on the delay. I’m going to look at the code in this PR again this week; I think there’s some small performance improvements that can be added (inadvertently caused by the side loading)

I’m not aware of away to force a convention for spacing and tabs with XCode. It might be good to do a separate formatting PR (no functional changes) to get all the code in a consistent convention?

________________________________

**Comment by ashnfb** [comment]
@cobarx I've made some improvements to the urlFilePath and fullscreenOptions for iOS.  PR is ready for review

ps. congratulations on your new job!

**Comment by cobarx** [comment]
@ashnfb Thanks!

Can you do another pass on this and update it. Unfortunately, I just merged the caching PR and now everything it out of sync. Also, make sure to document all the new functionality in the README file so people know it exists and how to use it.

I checked and it does appear we can configure per file / project spacing settings:
https://stackoverflow.com/questions/3216426/is-it-possible-to-set-indent-settings-in-xcode-per-project-or-per-file-even
I'll see about doing a PR for that shortly.

**Comment by ashnfb** [comment]
@cobarx closing this PR, and reopening with merged changes.

**Pull request closed without merging**
