### PR TITLE
fix(ios): call PictureInPicture callbacks with native controls

### LINKED ISSUE #3602: [BUG][PiP]: PictureInPicture callback are not called when PiP mode is entered from native controls
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

`onPictureInPictureStatusChanged` & `onRestoreUserInterfaceForPictureInPictureStop` are never call if we enter PiP mode from native control

### Reproduction

https://github.com/gkueny/NativeControlsPiPCallback

### Reproduction

Setup a video component with native control:

```tsx
<Video
  source={{
    uri: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  }}
  style={styles.backgroundVideo}
  resizeMode={ResizeMode.CONTAIN}
  controls={true} // this is important
  onPictureInPictureStatusChanged={() => console.log('onPictureInPictureStatusChanged)}
  onRestoreUserInterfaceForPictureInPictureStop={() => console.log('onRestoreUserInterfaceForPictureInPictureStop)}
/>
```

- Enter PiP mode from native control
    - notice that  `onPictureInPictureStatusChanged` log do not happen
- Exit PiP mode from native control
    - notice that  `onPictureInPictureStatusChanged` & `onRestoreUserInterfaceForPictureInPictureStop `logs do not happen

Issue also happen if we disable `controls` & go to fullscreen because fullscreen use native control

### PR DESCRIPTION
**Pull request by gkueny**
## Summary

When we enter PiP from native controls, `onPictureInPictureStatusChanged` is never called.
When we exit PiP after enter from native controls, `onPictureInPictureStatusChanged` & `onRestoreUserInterfaceForPictureInPictureStop` are never called.

Should fix https://github.com/react-native-video/react-native-video/issues/3602

### Motivation

Be notified when PictureInPicture status changed no matter how you enter this mode.
Has `onRestoreUserInterfaceForPictureInPictureStop` callback fire no matter how you exit PiP mode.

### Changes

We add RCTPlayerObserver as playerViewController delegate to be notified with PiP lifecycle

## Test plan

- Install https://github.com/gkueny/NativeControlsPiPCallback
- Reproduce the issue
- Install patch
```sh
yarn add react-native-video@https://github.com/gkueny/react-native-video.git#72ba955c464dc15a3db935de6fe8542c2b3cc0d3
```
- Validate that `onPictureInPictureStatusChanged` is called if you enter PiP mode from native controls
- Validate that `onPictureInPictureStatusChanged` is called if you exit PiP mode after enter it from native controls
- Validate that `onRestoreUserInterfaceForPictureInPictureStop `is called if you exit PiP mode after enter it from native controls

### CODE REVIEW

**Comment by gkueny** [comment]
I only handle enter & exit for now.

We also can handle `onRestoreUserInterfaceForPictureInPictureStop` callback too, but it's not so straightforward as enter & exit.
I will check to implement it in another PR when I will have more time

**Comment by gkueny** [comment]
I will test this change in our project. I will adjust this PR if needed after that

**Comment by gkueny** [comment]
@freeboub @KrzysztofMoch let me know if this bug fix seems ok for you.
On our side, this has been integrated into our app and corrects the issue raised with success.

**Review by KrzysztofMoch — APPROVED** [review]
Thanks, LGTM 🙌

**Pull request merged**
