### PR TITLE
Externally loaded text tracks not loading properly

### PR DESCRIPTION
**Pull request by brycnguyen**
I noticed that my text tracks stop loading with the introduction of [v6.0.0-beta.2](https://github.com/react-native-video/react-native-video/releases/tag/v6.0.0-beta.2). Looking at the condition that was introduced in the linting, I reverted it and saw that it loaded correctly after.

onLoad was also not including my externally loaded text track. My set up saves the text track with react-native-fs and then loads it in before playing the video player. 

#### Update the documentation
If you've added new functionality, update the README.md with an entry for your prop or event.
The entry should be inserted in alphabetical order.

#### Update the changelog
After you open the PR, update the CHANGELOG.md file with an entry pointing to your PR.

#### Provide an example of how to test the change
If the PR requires special testing setup provide all the relevant instructions and files. This may include a sample video file or URL, configuration, or setup steps.

#### Describe the changes
Partially reverts: https://github.com/react-native-video/react-native-video/commit/800aee09deb49c5ece01a6130d6364bcbdbda789, which was causing the text track to not load properly

Fixes onLoad not including externally loaded text track: https://github.com/react-native-video/react-native-video/issues/2953#issuecomment-1880535309

### CODE REVIEW

**Comment by brycnguyen** [comment]
@KrzysztofMoch tagging because the changes revolve around the linting introduced in https://github.com/react-native-video/react-native-video/commit/800aee09deb49c5ece01a6130d6364bcbdbda789

**Comment by KrzysztofMoch** [comment]
Thank you for your PR! Will look at it

**Comment by KrzysztofMoch** [comment]
@brycnguyen builds failure is cause by react-native issue https://x.com/Kelset/status/1744307922065150097?s=20

**Review by KrzysztofMoch — APPROVED** [review]
LGTM, Thanks for catching that! Can you rebase it onto master? I have fixed example builds

**Comment by brycnguyen** [comment]
@freeboub , could you let me know if the changes here make sense: https://github.com/react-native-video/react-native-video/pull/3461/files#diff-1536a22e8e888a1d8bccd1916bfec1af06373dd52ddb442c09544718e06a7193R1209 ?

**Comment by KrzysztofMoch** [comment]
@brycnguyen This change is good, there will never be both external & internal text track at the same time. You can see it here 
https://github.com/react-native-video/react-native-video/blob/11e5b756b14a2751352f97cde4fc027f441253ae/ios/Video/RCTVideo.swift#L756C1-L765C1
and here
https://github.com/react-native-video/react-native-video/blob/11e5b756b14a2751352f97cde4fc027f441253ae/ios/Video/RCTVideo.swift#L408C5-L434C6
that if external tracks are passed, you can't use internal tracks

**Comment by KrzysztofMoch** [comment]
@brycnguyen can I merge this ?

**Comment by brycnguyen** [comment]
@KrzysztofMoch sounds good! Feel free to merge.

**Pull request merged**
