### PR TITLE
Update for RN 0.7.0-rc.2

### PR DESCRIPTION
**Pull request by dhrrgn**
Use the public react-native interface for requiring internal modules where possible (causes warnings in 0.7.0-rc.2).

**Note:** There are several modules that are not yet exposed via the `react-native` public interface, so there will still be warnings.  Here are the ones you can still expect a warning from:

```
ReactNativeViewAttributes
StyleSheetPropType
NativeMethodsMixin
flattenStyle
merge
deepDiffer
```

### CODE REVIEW

**Comment by brentvatne** [comment]
Thanks for this @dhrrgn, going to get this in soon

**Comment by dhrrgn** [comment]
No problem. Figured it would wait until 0.7 was tagged. I assume this whole Packager/Public API situation is holding that back? (Sorry, not trying to hijack this issue for that question)

**Comment by brentvatne** [comment]
@dhrrgn - yeah I'm waiting to see what we are going to expose with the public API before making any decisions here

**Comment by dhrrgn** [comment]
👍

**Comment by brentvatne** [comment]
We're still waiting on this one @dhrrgn, haven't nailed this down yet

**Comment by edward** [comment]
@brentvatne Looks like this project works fine on RN 0.11.0 so you can close this issue.

**Comment by stereodenis** [comment]
@dhrrgn @brentvatne now we have RN 0.16. is this PR actual?

**Pull request closed without merging**
