### PR TITLE
refactor(android): migrate ReactVideoPackage to Kotlin

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
## Summary
Migrate ReactVideoPackage to Kotlin

### Motivation
Migrate the codebase from java to kotlin

## Test plan

### CODE REVIEW

**Review by freeboub — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]

**Comment by YangJonghun** [comment]
@seyedmostafahasani @freeboub @KrzysztofMoch 
`@JvmOverloads` is causing the following error
```
requireNativeComponent: "RCTVideo" was not found in the UIManager.
```

**Comment by seyedmostafahasani** [comment]
@YangJonghun I tested the app, but I didn’t encounter this error.

**Comment by YangJonghun** [comment]
@seyedmostafahasani 
Which version of react-native did you tested? Mine happened on 0.74.2

**Comment by seyedmostafahasani** [comment]
I tested with the basic example on the library. The version of react- native is 0.74.2.

**Comment by YangJonghun** [comment]
@seyedmostafahasani 
Thanks I'll tried to create reproduction

**Comment by seyedmostafahasani** [comment]
Did you succeed in recreating it with the basic example?

**Comment by YangJonghun** [comment]
@seyedmostafahasani
below is my reproduction steps
1. npx react-native init Sample (I tried with latest(0.74.3))
2. cd Sample && yarn add react-native-video@https://github.com/TheWidlarzGroup/react-native-video#3f11894c2b7d847b4690ae7e8f5f60c743609784
3. add `<Video />` within App.tsx (because this error occurred with mount)
4. run android
5. error occurred

**Comment by seyedmostafahasani** [comment]
@YangJonghun thank you for testing and informing me.
Let me do it.

**Pull request merged**
