### PR TITLE
Chore/fix build android

### PR DESCRIPTION
**Pull request by freeboub**
#### Describe the changes
Build: remove undeclared variable
sample: update yarn.lock

### CODE REVIEW

**Review by hueniverse — APPROVED** [review]

**Comment by jrhager84** [comment]
What does this address? I see it modifies eventEmitter. Does this address the lack of onPlaybackRateChanged as well?

**Comment by freeboub** [comment]
@jrhager84 it just fixes build, no behavior change in this PR

**Comment by jrhager84** [comment]
> 

There was a thread a while back that had the same issue as me and was marked 'completed' however - the issue (at least for me) still persists. Do you know if the onPlaybackRateChange method is now working on Android, and how I would go about getting it? I don't see any of these new merges being accessible for download. I'm on 5.2.0

**Comment by freeboub** [comment]
@jrhager84 on the previously merged PR, there is new event: onPlaybackStateChanged which may be interesting for you...
please check if there is an open ticket or open a new one

**Comment by jrhager84** [comment]
> @jrhager84 on the previously merged PR, there is new event: onPlaybackStateChanged which may be interesting for you... please check if there is an open ticket or open a new one

Where are these merged PRs going? There aren't any new versions of the repo.

**Comment by freeboub** [comment]
@jrhager84 please check master branch

**Comment by jrhager84** [comment]
@freeboub - I am checking the master branch. It's still at 5.2.0. Are we not incrementing the versions when we push new updates to the repo?

**Comment by hueniverse** [comment]
No, version gets incremented when a cut is made.

**Comment by jrhager84** [comment]
I'm not sure I understand. So I could have a _different_ 'version' of 5.2.0?

**Pull request merged**
