### PR TITLE
Load videos remotely from the network

### PR DESCRIPTION
**Pull request by qingfeng**
pls, review. thanks

### CODE REVIEW

**Comment by brentvatne** [comment]
@qingfeng - This is a good step forward, ultimately I would like to move towards supporting the same syntax as `Image` by having the `source` prop be an object with the `uri` param. This would work well with adding an `onLoadStart` callback too, so we could show some kind of loading indicator.

One nit and I'll merge - could you change indentations to two spaces instead of tabs?

Thanks! :smile:

**Comment by brianchirls** [comment]
Yes, good start. I think we'd need to scan for file extensions as well for local files. It may not always be mp4.

**Comment by qingfeng** [comment]
sorry, I modified the two space

**Comment by brentvatne** [comment]
Thanks :smile_cat:

**Comment by qingfeng** [comment]
:beer:

**Pull request merged**
