### PR TITLE
fix(RCTVideo.m): Fixed status bar disappearing issue

### PR DESCRIPTION
**Pull request by shahen94**
Closes out  #410

### CODE REVIEW

**Comment by ghost** [comment]
Best I can tell from blame history after looking at this is #410 was introduced in https://github.com/react-native-community/react-native-video/pull/103. I'm going to merge this in based on the number of upvotes in #410 and trust it doesn't cause any side effects. Sorry for your pains, @shahen94, and thanks for your persistence.

**Comment by shahen94** [comment]
@jhabdas Thank you for your quick response. Can i use this updated version with npm now ?

**Comment by ghost** [comment]
@shahen94 I don't have publish access to NPM and CI is not automated on this repo. you could ping one of the other members, though simply referencing the first 7 characters of the commit SHA in your package manifest will do the deed.

**Comment by aliemre** [comment]
This solution does not fix the issue. I tried on RN 0.46.3. Still status bar disappears after orientation changes. @shahen94 Any idea?

**Comment by shahen94** [comment]
This solution fixes an issue on our phones and simulators, i'm using rn 0.44, i didn't tried it on 0.46.

**Comment by aliemre** [comment]
I just added 
```_playerViewController = nil;```
to RCTVideo.m file (Exact line where you do changes). Is there anything needed to be done? NPM has not been updated. So I get still old version. Could you help about it? @shahen94

**Comment by shahen94** [comment]
change your package.json file to install package from github
```
react-native-video: "git+https://github.com/react-native-community/react-native-video.git"
```

**Comment by aliemre** [comment]
Hey @shahen94 thanks for your answer. However, I also tried in 0.44, but it's same. Would you mind to share a layout example from your working code base?

**Comment by zakster12** [comment]
It's not working with me as well. I tried with:
"react-native-video": "react-native-community/react-native-video#master",
but after fullscreen and rotation, the statusbar is gone.  [iOS]

On [Android] I even can't play video in fullscreen. this.player.presentFullscreenPlayer(); is working only on [iOS].

"react": "16.0.0-alpha.6",
"react-native": "0.44.3",

**Comment by shahen94** [comment]
full screen video doesn't supported on android version.
I didn't tried to rotate video, seems like we should remove reference on player controller somewhere.

**Comment by callmejm** [comment]
@shahen94 hi, I have a special request , how can I enter fullscreen and dismiss fullscreen without status bar in iOS

**Comment by shahen94** [comment]
@JayricMok 
In `RCTVideoPlayerViewController.m` add this lines

```
- (BOOL)prefersStatusBarHidden {
    return YES;
}
```

**Pull request merged**
