### PR TITLE
Fix iOS build caused by type mismatch

### PR DESCRIPTION
**Pull request by tironiigor**
## Description

Type `_eventDispatcher` as `RCTEventDispatcherProtocol` to match `bridge.eventDispatcher()` as the old type was causing the compiler to complain about types not matching

### CODE REVIEW

**Review by KestasVenslauskas — APPROVED** [review]

**Review by KestasVenslauskas — APPROVED** [review]

**Comment by baveku** [comment]
please merge this PR,
v6 cannot build on iOS

**Review by matinzd — APPROVED** [review]
Works fine for me as well!

**Comment by wood1986** [comment]
This PR breaks the current main branch. How come this PR can get it? Which react-native version have RCTEventDispatcherProtocol?

**Comment by freeboub** [comment]
@wood1986 cqn it be link to react native version ?

**Comment by tironiigor** [comment]
@wood1986 we're using react native 0.69 and it's working fine. What is your version?

**Comment by wood1986** [comment]
I am trying to build example/basic ios. This is using 0.63.4
See https://github.com/react-native-video/react-native-video/blob/master/examples/basic/yarn.lock#L5810

**Pull request merged**
