### PR TITLE
Always check for hideShutterView before showing shutterView

### PR DESCRIPTION
**Pull request by tironiigor**
# Always check for hideShutterView before showing shutterView

## Changes

For every call, we made to set `shutterView` visibility to VISIBLE we should check for the `hideShutterView` variable to avoid flashing a black screen. This makes the Android consistent with iOS

## Testing

1. Pass `hideShutterView={true}` to the component
2. Before this fix it would flash a black screen before hiding it

### CODE REVIEW

**Review by andac-ozcan — APPROVED** [review]

**Review by freeboub — CHANGES_REQUESTED** [review]
Ok for me, can you just fix the changelog please ?

**Comment by tironiigor** [comment]
@freeboub done!

**Comment by tironiigor** [comment]
@freeboub should it be alpha1 or alpha2?

**Comment by hueniverse** [comment]
We're still working on alpha1.

**Comment by tironiigor** [comment]
Done @hueniverse @freeboub

**Pull request merged**
