### PR TITLE
fix: fix the memory leak

### LINKED ISSUE #2906: iOS RCTVideoPlayerViewController wont call deinit when unmount
# Bug

RCTVideoPlayerViewController wont call deinit when unmount. This causes the memory leak

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 488.25 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /private/var/folders/xn/9sz2plkj3wbf2lj_ths6_ykr0000gn/T/xfs-aaedb8c8/node
    Yarn: 3.2.4 - /private/var/folders/xn/9sz2plkj3wbf2lj_ths6_ykr0000gn/T/xfs-aaedb8c8/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    Watchman: 2022.10.10.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/wood/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.3

## Steps To Reproduce

1. `git clone https://github.com/wood1986/react-native-fullscreen-example.git`
2. `git checkout bug/memory-leak`
3.  `yarn && cd ios && pod install && yarn ios`
4. Tap 'Toggle' Button to unmount/mount the Video component
...

## Expected behaviour

1. xcode console should print `RCTVideoPlayerViewController deinit` when unmount

## Reproducible sample code

https://github.com/wood1986/react-native-fullscreen-example/tree/bug/memory-leak

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

### PR DESCRIPTION
**Pull request by wood1986**
fix #2906 and #2809

### CODE REVIEW

**Comment by freeboub** [comment]
looks OK for me, can you add a small comment in changeLog please ?

**Comment by wood1986** [comment]
done

**Comment by freeboub** [comment]
looks OK for me, should I merge this PR ?

**Comment by wood1986** [comment]
I think this can be merged. But do not publish a new version until we resolve #2908

**Comment by cguino** [comment]
The memory leak still exists.

A quick way to reproduce is using this sample made by @wood1986 
https://github.com/wood1986/react-native-fullscreen-example/tree/bug/memory-leak

Add a breakpoint in deinit ( RCTVideo l.161 ), it's never called

- Some `[weak self]` are missing  
- I found two delegate that are not weak. (delegate should always be weak, otherwise it makes a retain cycle)

**Comment by VMBindraban** [comment]
@cguino Was this leak fixed in a future release? I am currently running into weak reference overflow errors.

**Pull request merged**
