### PR TITLE
Introducing custom/native/embed skins

### PR DESCRIPTION
**Pull request by PublicParadise**
This PR introduces a new property called `controls` that echoes HTML5's `<video>` tag attribute. For more details see [HTML <video> controls Attribute](http://www.w3schools.com/tags/att_video_controls.asp). The basic idea is that  when `controls` is true the native video controls should be displayed.
### VideoPlayer Example

The VideoPlayer Example's default for `controls` is set to false:

screen shot 2015-12-21 at 7 08 40 pm
### Custom Controls (default)

`controls` is set to `false`.

screen shot 2015-12-21 at 6 58 06 pm
### Native Controls - fullscreen mode

`controls` is set to `true`.

screen shot 2015-12-21 at 6 58 44 pm
### Native Controls - embedded

`controls` is set to `true`.

screen shot 2015-12-21 at 6 59 03 pm
### Superseding PRs

This PR supersedes two prior PRs of mine:
- Fix for Example/VideoPlayer (issue 117), https://github.com/brentvatne/react-native-video/pull/118
- Switching from progressTimer to addPeriodicTimeObserverForInterval, https://github.com/brentvatne/react-native-video/pull/68
### Known Problems
- no Android support
- switching back and forth between `custom` and `native` at runtime might leave the `VideoPlayer` in an inconsistent state, i.e. the progress bar is not not reset when switching from `custom` to `native`.

### CODE REVIEW

**Comment by stereodenis** [comment]
:muscle:

**Comment by brentvatne** [comment]
Neat! The commit history looks strange though -- it includes a bunch of commits that are already part of master. Could you rebase this on master?

**Comment by PublicParadise** [comment]
@brentvatne: better?

**Comment by brentvatne** [comment]
lgtm!

**Comment by PublicParadise** [comment]
@brentvatne Sweet, thanks man!

**Pull request merged**
