### PR TITLE
Implement Interactive Media Ads (IMA) SDK 

### PR DESCRIPTION
**Pull request by robbywh**
Hi everyone,

I have PR to play ad on video player with Interactive Media Ads (IMA) SDK. 
Please Review my PR.

Best Regards,
Robby Widyahartono

### CODE REVIEW

**Comment by benoitdion** [comment]
Hi @RobbyWH, this overall looks great but unfortunately, we don't want to make IMA a required dependency for all users of react-native-video. 

Eventually, I'd like to enable extensions like this via an extension mechanism. This would look something like:

```
<Video>
   <ImaPlugin someConfigValue="foo" />
</Video>
```

**Comment by robbywh** [comment]
Hello @benoitdion, thank you for your response.

is there a development process that is being carried out?
If so, when will this feature be released?

**Comment by ayciceksahin** [comment]
Hi @benoitdion When can we reached it out ? 
Or is there a development process that is being carried out? as @RobbyWH said

**Comment by sidferreira** [comment]
@RobbyWH @ayciceksahin I had a PR to work with it #1740

**Comment by jeffelector** [comment]
hi, what is the status of this?

**Comment by robbywh** [comment]
@jeffelector i'm gonna close this PR, because react-native-video doesn't want to make IMA SDK become required dependency

**Comment by scott-thrillist** [comment]
@RobbyWH why don't you fork this project? Many of us want ad support

**Comment by sidferreira** [comment]
@scott-thrillist check #1740

**Comment by robbywh** [comment]
@scott-thrillist I have forked this project, you can check in here: https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk

**Comment by liquidvisual** [comment]
@RobbyWH This is excellent, thanks! What version of react-native-video does it use? (sorry if that's a newb question)

**Comment by robbywh** [comment]
Your welcome @liquidvisual , I still use version 5.1.0-alpha1

**Pull request closed without merging**
