### PR TITLE
Added `requestOrientationInFullscreen` property

### PR DESCRIPTION
**Pull request by incetarik**
Added `requestOrientationInFullscreen` property to control whether the activity should request landscape/portrait orientation natively, according to the `fullscreen` property.

### CODE REVIEW

**Comment by jensellfors** [comment]
Isn't this the same as `fullscreenOrientation` but for Android? Can we reuse the same prop?

**Comment by incetarik** [comment]
> Isn't this the same as `fullscreenOrientation` but for Android? Can we reuse the same prop?
Hi, long time passed and I'm not sure whether this thing had been solved in `react-native-video`. The problem was with Android. Setting `fullscreen` property was not actually making it fullscreen, but just setting some window flags if I'm not wrong, which makes the status bar and navigation bar disappear but not rotating the screen (requesting landscape orientation). This request was just for adding this property to reduce the work needed by the code to make the video full screen on landscape

**Comment by r0b0t3d** [comment]
@incetarik You could try #2073. With those changes, `fullscreenOrientation` can be applied for `ExoPlayer Android`.

**Comment by incetarik** [comment]
@r0b0t3d As you can see that the PR is created pretty long ago, and if your PR contains the things I was tried to fix/add, then of course this PR should be closed in that case, if yours is working. My intention was also adding the actual full screen flags on the Android side. Please tell me whether your PR contains such changes and this PR is already covered there so this could be closed.

**Comment by r0b0t3d** [comment]
@incetarik The solution in that PR is start another activity to show full screen video. It contains code to request for the orientation that you set via `fullscreenOrientation`.
```
String orientation = getIntent().getStringExtra(EXTRA_ORIENTATION);
         if ("landscape".equals(orientation)) {
             setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
         } else if ("portrait".equals(orientation)) {
             setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT);
         }
```

**Comment by incetarik** [comment]
Thank you for replying @r0b0t3d , if you show that video in **another** activity, isn't it causing another navigation event? I'm thinking about whether this could also affect applications that use native navigation libraries.

**Comment by r0b0t3d** [comment]
I was using `react-navigation/native` along with this PR and still not see the problem then. You could give it a try.

**Comment by incetarik** [comment]
I think about `react-native-navigation` -like libraries which cause developers to change their boot/startup code. Because the layout will be based on whatever the library will provide so pushing another activity might cause a corrupted navigation data for them.

**Comment by r0b0t3d** [comment]
Not sure that I got you. But in fullscreen video activity, it just show default controls from ExoPlayer. And you could customize such controls but it will be in native android.

**Pull request closed without merging**
