### PR TITLE
Raising error for source exception

### PR DESCRIPTION
**Pull request by vengadesh**
Handle cases when the file is not a valid media file.

### CODE REVIEW

**Comment by treemore** [comment]
it is work!! thank you

**Comment by manask88** [comment]
@mattapperson any chance we could merge this guy soon?

**Comment by thomasobrien99** [comment]
+1

**Comment by manask88** [comment]
Hey @mattapperson, any chance we could have this guy merged soon?

**Comment by danlopez** [comment]
Any updates on this? It would be really useful for me to have access to this?

**Pull request merged**
