### PR TITLE
fix ios block ui issue

### LINKED ISSUE #2986: Video freeze UI until video is loaded on IOS, scroll is stuck
# Bug

Happy new year to all !

I am the creator of **SoSkills** app which is available on **Apple** and **Android**
**SoSkills** is a video sharing community application in the gaming ecosystem.
More info here [https://soskills.io](https://github.com/react-native-video/react-native-video/issues/url)

Keep in mind user can swipe through videos on the Home page with FlatList as Instagram short, TikTok etc

When user swipe to the bottom, app is going to load new videos by doing a request to the server for having videos object from BDD with uri property which is the path of the video on Amazon, so the file is not get by my server but directly with react-native-video (uri is with https)
So when user swipe, new item in the Flatlist are rendered and Video component start to init video with new uri from Amazon.
Request take some time when there's an average connexion or bad connexion, UI will freeze, app will be stuck and user can't do anything on the app until video is loaded by react-native-video.

No hidden process or work is doing during the scroll, just react-native-video is blocking the JS thread and UI freeze

## Platform

- Android with Redmi Note 10S phone
- IOS with Iphone 12 pro

## Environment info
Screenshot 2023-01-04 at 15 42 58

React native: 0.67.3
Library version: [v6.0.0-alpha.4]

## Steps To Reproduce

Use average connexion or bad connexion which is the best scenario.
Create a FlatList with with 3 item where item is taking all the viewport so one item by viewport.
Get new data when item + 1 === item.length and get new data, ui will freeze.

## Expected behaviour

UI with no freeze, scroll still possible even if Video component is loading the video as Android with their video player.
On Android, if video is not loaded, user has just to wait but if he wants to scroll he can, without being stopped.

## Reproducible sample code

**SoSkills** is a private company, code is not open source so can't do that but i shared screenshot and video

## Video sample

This example is done with my Iphone 12 pro on 4g which is average so if you don't have good connexion, it's really not good ! 

https://user-images.githubusercontent.com/3983160/210596138-0d291326-06ba-4cae-bfcc-85e260be4add.mp4

### PR DESCRIPTION
**Pull request by vemarav**
closes #2986 #3058

### CODE REVIEW

**Comment by vemarav** [comment]
@freeboub tested on fullscreen & flatlist

**Comment by marcel-happyfloat** [comment]
Works in my app 👍. Thank you very much!

**Comment by vemarav** [comment]
> Works in my app 👍. Thank you very much!

make your users happy with delightful experience 🚀

**Comment by stefanahman** [comment]
This solves the issue (on my physical phone), but now I have a problem of streaming videos in the simulator while developing. Anyone knows the issue behind this?

**Comment by vemarav** [comment]
@stefanahman 
> This solves the issue (on my physical phone), but now I have a problem of streaming videos in the simulator while developing. Anyone knows the issue behind this?

Use ios 16.1 or lower on simulator

**Comment by ColtraneNadler** [comment]
what version is this fixed in ? 
im currently using `5.2.1` and it freezes the UI momentarily when starting to play the video.

**Comment by freeboub** [comment]
@ColtraneNadler try with v6.0.0-RC0

**Comment by EuSet** [comment]
faced this issue using 6.1.1 version

**Comment by himanshut230** [comment]
facing this issue in (v6.0.0, v6.1.2) versions. In v6.0.0-alpha.7 it is working fine but there are other issues in this version and it is not stable.

**Comment by gerson** [comment]
I'm having the issue in (v6.0.0, v6.1.2) versions. In v6.0.0-alpha.7 it is working fine cannot go back since there are another issues in this version and I would like to use the stable one, any update?

**Pull request merged**
