### PR TITLE
Feature: playing audio over earpiece

### PR DESCRIPTION
**Pull request by liviu-padurariu**
Feature: playing audio over earpiece [#2887](https://github.com/react-native-video/react-native-video/issues/2887)

-  updated docs and changelog

#### Provide an example of how to test the change

`<Video ... audioOutput={'earpiece'} />`

#### Focus the PR on only one area

This PR allow to change the audio output to the earpiece.

#### Describe the changes

Change the native audio output based on the `audioOutput` prop.

### CODE REVIEW

**Comment by freeboub** [comment]
Thank you for this PR !
Code looks good, but I have few questions:
- The earpeace is only for JACK output ? 
- Will it work with bluetooth speakers ?
- Do you use an external package to detect if an earpiece is connected ?
I think these answers can be doc addon.

A plus, would be integration in sample, but it is not mandatory

**Comment by evoactivity** [comment]
@freeboub I believe this is to play from the speaker used normally for phone calls.

**Comment by liviu-padurariu** [comment]
@evoactivity  Yes, you are right.

@freeboub `earpiece` is the earpiece speaker of the phone. sorry for the confusion. I can rename it, if you have any suggestions.

**Comment by freeboub** [comment]
ok, great I understood, wording is OK to me :) 
Just one missing answer: Do you use an external package to detect if an earpiece is connected ?
maybe another package include such feature ?
https://stackoverflow.com/questions/52127683/check-if-headset-is-connected-on-different-api-levels

**Comment by liviu-padurariu** [comment]
no, I didn't use any external packages.

**Review by freeboub — APPROVED** [review]

**Comment by freeboub** [comment]
I approuve the PR, but I cannot test as the USB connector of my phone is broken ...
I would like a confirmation, you don't reapply to audio output at playback start, is it working after playback change ?
sample use case:
- start playback of content 1
- change audio output to earpiece
- stop playback but putting an empty url
- start another playback
- > here is the audio output correctly reapplied ?
Thank you

**Comment by freeboub** [comment]
Has been merged in another PR

**Pull request closed without merging**
